### ISSUE TITLE
Some small tips about the yaml header

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#10]
# list of some tricks about rmarkdown yaml header
- [ ] how to change the title in Rmarkdown file with r code ? One solution, see this [SO question](https://stackoverflow.com/questions/31861569/setting-document-title-in-rmarkdown-from-parameters)
- [ ] change output file from `knit:` yaml param. see #151 and see [SO](https://stackoverflow.com/a/28785774/3436535), this [note](https://github.com/lmmx/devnotes/wiki/Rmarkdown-custom-knit-hook-to-compile-a-multi-part-document) and related [GH issue](https://github.com/rstudio/rmarkdown/issues/277)
- [x] Current date in YAML header ([SO post](https://stackoverflow.com/questions/23449319/yaml-current-date-in-rmarkdown))
- [ ] subtitle field ([SO post](https://stackoverflow.com/a/33680803/3436535))
- [ ] line break in title using `|` ([SO post](https://stackoverflow.com/questions/28895109/how-can-i-force-a-line-break-in-rmarkdowns-title), [SO post](https://stackoverflow.com/questions/29152082/insert-a-linebreak-in-title))
- [ ] Split title ([SO post](https://stackoverflow.com/questions/30537515/split-the-title-onto-multiple-lines))

_We could separate in several issues instead if you prefer_

**Comment by RLesur** [comment]
Suggestion: pass a custom function to `df_print` ([SO post](https://stackoverflow.com/a/54190736/6500804)), see also `?yaml::yaml.load`.

**Comment by cderv** [comment]
Evaluate R expression in yaml header : https://github.com/rstudio/rmarkdown-book/pull/54

**Comment by cderv** [comment]
`knitr:` field in yml also added in https://github.com/yihui/rmarkdown-cookbook/commit/4b2d2e4023ee561ab3bef21df1e7b0cfd62e3697
