### ISSUE TITLE
How to use README.rmd in a package and store images without CRAN NOTES

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#108]
This is a use case that could of interest for 📦 developer. It seems good practice to store image in 
"man/figures/". 

This is done now very quickly with `usethis::use_readme_rmd()` that include the correct setup in the [template](https://github.com/r-lib/usethis/blob/master/inst/templates/package-README)

Based on : https://stackoverflow.com/questions/44113759/note-or-warning-from-package-check-when-readme-md-includes-images/47605343#47605343

**Comment by dr-harper** [comment]
Think we could add a general section on "Using R Markdown for your GitHub README" or something like this. This would make it more relevant to a wider audience of people as lots of people share repos on github. This could then get more specific to target things specific to package developers.

Here is an [example README](https://github.com/tidyverse/ggplot2/blob/master/README.Rmd) for ggplot which creates the README.md file. This also shows how you can include a logo in the top right corner of the README.
