### ISSUE TITLE
load extra latex package for kableExtra ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#109]
I open this to discuss with @haozhu233 

In this [SO question](https://stackoverflow.com/questions/46080853/why-does-rendering-a-pdf-from-rmarkdown-require-closing-rstudio-between-renders) (top 188), you explain that some Latex package need to be added to Rmakdown yaml header
``` r
kableExtra::kableExtra_latex_packages()
#> header-includes:
#>   - \usepackage{booktabs}
#>   - \usepackage{longtable}
#>   - \usepackage{array}
#>   - \usepackage{multirow}
#>   - \usepackage[table]{xcolor}
#>   - \usepackage{wrapfig}
#>   - \usepackage{float}
#>   - \usepackage{colortbl}
#>   - \usepackage{pdflscape}
#>   - \usepackage{tabu}
#>   - \usepackage{threeparttable}
#>   - \usepackage{threeparttablex}
#>   - \usepackage[normalem]{ulem}
#>   - \usepackage{makecell}
```

Is it still the case ? Is it something we should mentioned maybe, when we talk about kableExtra in #8  ? 

Thanks.

**Comment by dr-harper** [comment]
This is explained nicely on page 3 of the documentation [here](https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf):

> If you are using a recent version of rmarkdown, you are recommended to load this package entirely via library(kableExtra) or require(kableExtra) because this package will load all necessary LaTeX packages, such as booktabs or multirow, for you automatically. Note that, if you are calling functions from kableExtra via kableExtra::kable_styling() or if you put library(kableExtra) in a separate R file that is sourced by the rmarkdown document, these packages won’t be loaded. Furthermore, you can suppress this autoloading behavior by setting a global option kableExtra.latex.load_packages to be FALSE before you load kableExtra.

Definitely worth adding to the section on `kableExtra` in the book as I still see this appearing all over StackOverflow.

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/kableextra.html
