### ISSUE TITLE
Understand and deal with render directory of Rmarkdown file

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#11]
It is always something that seems to be difficult to fully understand. Some explanation and example could be useful I think.

* By default, it renders in the directory of the rmarkdown file
* Some people offer solution for another approach ([ezknitr](https://github.com/ropensci/ezknitr) 📦 
* RStudio IDE since 1.1 provides some option to change the way it behave when clicking on knit button (see [blog post anouncement](https://blog.rstudio.com/2017/09/13/rstudio-v1.1---the-little-things/)
* `rmarkdown::render' has an argument `knit_root_dir`
* Option can be set in a chunk with `knitr::opts_knit$set(root.dir = )`

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html
