### ISSUE TITLE
Example about externalization of chunk in R script

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#112]
knitr 📦 has a `read_chunk` function that allow to source an R file and call them in chunk in an Rmd document. 

See [knitr example 113](https://github.com/yihui/knitr-examples/blob/master/113-externalization.Rmd) and [demo on externalization](https://yihui.name/knitr/demo/externalization/)

This is related in topic to #14 and child option

## Related SO question

https://stackoverflow.com/questions/14796501/is-it-possible-to-call-external-r-script-from-r-markdown-rmd-in-rstudio

## Related knitr example

- knitr Demo : https://yihui.name/knitr/demo/externalization/
- Example : https://github.com/yihui/knitr-examples/blob/master/113-externalization.Rmd

**Comment by cderv** [comment]
Additions in this in 26fbc5b

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/read-chunk.html
