### ISSUE TITLE
conditionally hide/show markdown text in a Rmardkown document

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#113]
Use [`asis` engine](https://github.com/yihui/knitr/blob/6c614153278be4de83632742b357e9a77ef45abb/R/engine.R#L392) and chunk option `echo`.

````
```{asis, echo=FALSE}
Some arbitrary text.

1. item
2. item

Change echo=TRUE or FALSE to display/hide this chunk.
```
````
https://stackoverflow.com/questions/32944715/conditionally-display-block-of-markdown-text-using-knitr

**Comment by dr-harper** [comment]
This is really cool! I like the use case provided where they want to have two versions of the same document: one with solutions and the other without. Definitely one to include.

**Comment by cderv** [comment]
Related to #7 and knitr engines

**Comment by cderv** [comment]
Added in https://github.com/yihui/rmarkdown-cookbook/commit/aa37cb1cc6e19e1a575647270ac4ff1c176768d6
