### ISSUE TITLE
Idea : About Latex and use of tinytex ?

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#115]
I think we could recommend `tinytex` in the cookbook for those not so familiar with Latex, and that uses it only for rmarkdown maybe. 

The only current documentation is here right now: 
https://yihui.name/tinytex/

More generally, some tips and tricks about latex configuration could be helpful. 

# Related SO question

* about tinytex in the answer : https://stackoverflow.com/questions/48224162/knitr-wont-compile-pdf-error-in-toolsfile-path-as-absoluteoutput-file
* about latex package (https://stackoverflow.com/questions/27514610/how-can-i-use-latex-packages-in-r-markdown-beamer)

**Comment by dr-harper** [comment]
I agree with this. I will adapt the documentation from the website and add this to the installation section.

**Comment by dr-harper** [comment]
Added some content in 3e515ff12911143d250acf7377cb4a9570575416. 

I was not sure whether we should recommend that all users use it by default. I personally still use a full LaTeX distribution, this is partly because I got used to doing it and also use LaTeX for other work.

**Comment by cderv** [comment]
> I was not sure whether we should recommend that all users use it by default.

For new users it is really easier, all the more if you don’t know much about latex and I think @yihui recommends it. Don’t you ?

**Comment by yihui** [comment]
Of course, I do strongly recommend it :)

**Comment by cderv** [comment]
Adding some ideas here: 

* Explain TinyTex emulation of latexmk
* Explain how to to configure latexmk behavioir : https://mg.readthedocs.io/latexmk.html#configuration-files
