### ISSUE TITLE
About word output

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#117]
We could have a chapter about word output. I think there are some things to say. 

New package like [`worded`](https://github.com/davidgohel/worded) are not well known but offer know feature that complement well the `word_document` format. 

Related to #47

**Comment by cderv** [comment]
Template in word: https://stackoverflow.com/questions/29440007/changing-word-template-for-knitr-in-rmarkdown

**Comment by dr-harper** [comment]
Yeah, I agree that having a section on Word outputs could be useful 👍 . As much as I prefer using HTML and PDF, I think Word can act as a good gateway for people to get into R Markdown.

**Comment by dr-harper** [comment]
I have added a chapter shell for word: 87a9a00e30b68ffea074b6f73b5799eef439130a

**Comment by cderv** [comment]
Word is important especially in corporate environment. You can do a lot already but it is not known. 
New pandoc version has also new feature for office document.
Some projects are willing to go further like worded I linked before, and more recently [redoc](https://github.com/noamross/redoc)

I can do this part - you can assign to me. (It seems I do not have the correct write access as I can't assign an issue to myself)

**Comment by dr-harper** [comment]
> I can do this part - you can assign to me. (It seems I do not have the correct write access as I can't assign an issue to myself)

I was about to ask whether you could assign things to yourself now, but looks like you beat me to it!

Looking forward to seeing what you come up with 😄

**Comment by dr-harper** [comment]
Completely agree, merge requests sound good to me 👍
