### ISSUE TITLE
add something about knit_child ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#123]
We talk about child in [this chapter](https://dr-harper.github.io/rmarkdown-cookbook/multi-file-documents.html).

[Knitr demo](https://yihui.name/knitr/demo/child/#using-knit-child-with-inline-r-code) also show how to use `knit_child` to add a child document in inline code. 

This is related to #67 where `knit_child` is used.  and also to #14 

## Related knitr example

- Demo: https://yihui.name/knitr/demo/child
- knitr example 1: https://github.com/yihui/knitr-examples/blob/master/020-for-loop.Rnw
- knitr example 2: https://github.com/yihui/knitr-examples/blob/master/021-ggplot2-geoms.Rnw

**Comment by dr-harper** [comment]
I notice the documentation of the package and the examples both refer to the Sweave format. It is slightly opinionated, but I see there being little need for this format anymore as I always think it causes more confusion to uses.

Will try and see if it works within an `.Rmd` workflow.

**Comment by cderv** [comment]
I already have some examples on this from community and discussion. This is a part I can work on.

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html
