### ISSUE TITLE
How to use a figure caption based on a current chunk value ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#125]
Basically, this is a knitr example
https://github.com/yihui/knitr-examples/blob/master/019-fig-caption.Rnw

And it uses `eval.after` options.

Related to #25

**Comment by dr-harper** [comment]
This example actually covers a few different features. I think`eval.after` could be useful. Adapting the example:

````
When `fig.cap` needs to use objects in the current chunk, we need to set the eval.after options so the objects are available when `fig.cap` is used:

```{r}
library(knitr)
# evaluate fig.cap after a chunk is evaluated
opts_knit$set(eval.after = 'fig.cap')
```

Dynamically generate a figure caption:

```{r t-test, fig.cap=paste('The P-value is', format.pval(t.test(x)$p.value)), fig.height=2.5}
x <- rnorm(30)
par(mar=c(4, 4, .1, .1)); hist(x, main='')
```
````

The example also mentions that [Figure environments in LaTeX](https://github.com/yihui/knitr-examples/blob/master/019-fig-caption.Rnw#L25-L29)  can be controlled. I haven't actually explored whether this could be of use but I will check it out further.

**Comment by cderv** [comment]
New example for inspiration
https://community.rstudio.com/t/how-can-i-include-r-code-in-an-rmarkdown-figure-caption/21429/2

**Comment by cderv** [comment]
Related about figure caption : #191

**Comment by yihui** [comment]
I think it will be clearer if the value required for the figure caption is calculated in a _previous_ chunk, so we don't have to set the `eval.after` option (which sounds too technical to me). As long as the value is available to the next chunk, the `fig.cap` can be any R expression: https://bookdown.org/yihui/rmarkdown-cookbook/chunk-variable.html
