### ISSUE TITLE
How to optimize PNG output with knitr and optipng

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#126]
In fact, this is an included option I did not know about

See this example
https://github.com/yihui/knitr-examples/blob/master/035-optipng.Rmd

This a hook (related to #53) document in `help("hook_pdfcrop", package = "knitr")` (see [source](https://github.com/yihui/knitr/blob/master/R/hooks-extra.R))

**Comment by cderv** [comment]
There is also a knitr example related to this
https://github.com/yihui/knitr-examples/blob/master/035-optipng.Rmd

**Comment by yihui** [comment]
Added via f523514.
