### ISSUE TITLE
How to separate code chunk and its results with `ref.label`

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#13]
Advance tip that I discovered and should be mentioned in a cookbook : 
* chunk option `ref.label` to get the code from another named chunk
* seen in this [this blog post](https://www.garrickadenbuie.com/blog/2018/08/16/decouple-code-and-output-in-xaringan-slides/)
* Example : fully customize some slide output to separate code and results. (see blog post for xaringan example)

## Related knitr example

- Demos : https://yihui.name/knitr/demo/reference/

**Comment by cderv** [comment]
Another use case : Put the code at the end of the document instead of above result
+ https://stackoverflow.com/questions/30242753/defer-code-to-end-of-document-in-knitr
+ https://stackoverflow.com/questions/28458384/use-rmarkdown-knitr-to-hold-all-code-until-the-end

**Comment by cderv** [comment]
Another case is to make an executive summary or just use some value in text with r inline code **before** it is created in a chunk after.
https://stackoverflow.com/questions/23570718/creating-summaries-at-the-top-of-a-knitr-report-that-use-variables-that-are-defi

**Comment by cderv** [comment]
Related knit example  using `load_cache`
https://github.com/yihui/knitr-examples/blob/master/114-load-cache.Rmd

**Comment by cderv** [comment]
A question related to this in [rstudio community](https://community.rstudio.com/t/calling-variables-before-theyre-declared-in-a-notebook/19675/8)

**Comment by cderv** [comment]
[x} `load_cache()` has been added in 90995c730f50d057323716e08c47b8b4546de9f0

**Comment by cderv** [comment]
`ref.label` is mentioned here https://bookdown.org/yihui/rmarkdown-cookbook/code-appendix.html

Can `ref.label` be another recipe in addition to `load_cache()` to [use an object before it is created](https://bookdown.org/yihui/rmarkdown-cookbook/load-cache.html) ? 
From this example https://github.com/yihui/rmarkdown-cookbook/issues/13#issuecomment-429306652

Other than that, we can close.

**Comment by yihui** [comment]
`ref.label` definitely deserves its own introduction. Done now. Thanks!
