### ISSUE TITLE
Recipes to convert tiktz figures to png

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#133]
I don't know if it is useful or not as I don't do a lot of Latex. I let you decide.

```r
knit_hooks$set(tikz2png = function(before, options, envir) {
  # use this hook only for dev='tikz' and externalized tikz graphics
  if (before || options$dev != 'tikz' || !options$external || options$fig.num == 0) return()
  figs = knitr:::all_figs(options, ext = 'pdf')  # all figure names
  # note the tikz2png option is the extra parameters passed to 'convert'
  for (fig in figs) {
    system(sprintf('convert %s %s %s', options$tikz2png, fig, sub('\\.pdf$', '.png', fig)))
  }
})
```
https://github.com/yihui/knitr-examples/blob/master/047-tikz-png.Rnw

**Comment by dr-harper** [comment]
I might put this in the category of "could be useful, but probably not for many people". @yihui wrote the original function so has the strongest opinion, so I will leave it open until he reviews it. 

I see you have linked this to the [knitrhooks](https://github.com/nathaneastwood/knitrhooks/issues/20) so will probably let it rest there for now.

**Comment by yihui** [comment]
I think it is useful, but I'd use the R **magick** package to do the conversion instead of requiring users to install ImageMagick.

**Comment by dr-harper** [comment]
Thanks for the input! I will check out the **magick** package. Installing ImageMagick was one of the things putting me off from the original solution.

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/graphical-device.html
