### ISSUE TITLE
Break long line with Latex

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#135]
If we talk about breaking long lines, here is a trick for knitr example
https://github.com/yihui/knitr-examples/blob/master/066-listings-breaklines.Rnw

**Comment by dr-harper** [comment]
This is definitely something to discuss!  The solution linked unfortunately only works within the Sweave output, and doesn't seem to translate to R Markdown.  There are lots of similar posts out there around this issue:

- https://github.com/yihui/knitr-examples/blob/master/077-wrap-output.md
- https://stackoverflow.com/questions/26210656/in-r-markdown-in-rstudio-how-can-i-prevent-the-source-code-from-running-off-a-p
- https://stackoverflow.com/questions/40030245/how-to-wrap-a-long-string-when-making-a-pdf-document-in-markdown-knitr
- https://stackoverflow.com/questions/14901781/how-to-wrap-text-in-r-source-with-tidy-and-knitr

Using the `tidy` hook can work in some cases, but it won't hard-wrap code.  Seems like a more complex one this one so will do it at some stage!

**Comment by cderv** [comment]
FWIW in a way this relates also to #111 and #118. I agree this need some study.

**Comment by yihui** [comment]
Added in 1adda85.
