### ISSUE TITLE
Add footer to HTML

### ISSUE THREAD

**Issue by dr-harper** [yihui/rmarkdown-cookbook#146]
A [useful post](https://holtzy.github.io/Pimp-my-rmd/) full of ways to style R Markdown documents. Particularly like point 6 on adding a footer to the HTML document:

![image](https://user-images.githubusercontent.com/20046224/49507038-80c52300-f877-11e8-9783-5c8002834af8.png)

Expanded a bit on SO to show how this HTML can directly link to the `author` YAML field: https://stackoverflow.com/questions/50037340/using-the-author-field-of-r-markdown-in-footer-html

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/include-html.html
