### ISSUE TITLE
How to add a page break in a Rmd document 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#15]
## Using markdown syntax ? 
use `******` or `------`

- [x] to be checked if it works...

## Using Latex
Add directly `\newpage` or `\pagebreak` in the document. 
[about Latex pagebreak](http://www.personal.ceu.hu/tex/breaking.htm)

## Using Html
Add a pagebreak tag. But not really useful...

## How to make it conditional ? 
Use `knitr::is_latex_output()` to test the format of the document and add into a chunk ? 
````r
```{r pagebreak, results='asis', eval=is_latex_output()}
cat('\\pagebreak')
```
````

Could also be used in a child document, loaded with `child` chunk option when needed.

## Related SO questions
* https://stackoverflow.com/questions/25240541/how-to-add-newpage-in-rmarkdown-in-a-smart-way
* https://stackoverflow.com/questions/16173995/knitr-rmd-page-break-after-n-lines-n-distance

**Comment by mikey-harper** [comment]
Good idea.

From my tests `******` and `-------` only add horizontal lines but don't create a line break.

I am not really sure there is a need for the conditional section. R Markdown will ignore HTML and LaTeX commands if not knitting to those formats. As an example:

````
---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
---

## Chapter 1

Some text

<P style="page-break-before: always">
\newpage

# Chapter 2

More text
````

It is still an area which requires clarification though.

**Comment by cderv** [comment]
Related but not sure it needs its own ticket:
https://stackoverflow.com/questions/24425786/how-to-add-whitespace-to-an-rmarkdown-document
`\newpage` is mentionned

**Comment by cderv** [comment]
https://stackoverflow.com/questions/31830974/inserting-a-page-break-within-a-code-chunk-in-rmarkdown-converting-to-pdf

**Comment by cderv** [comment]
About newline, that could go with pagebreak
https://stackoverflow.com/questions/43239868/add-blank-line-to-word-output-rmarkdown
also related to #117

**Comment by cderv** [comment]
You can also do it manually Using pandoc raw attributes if you know the syntax for the output document 
See https://community.rstudio.com/t/starting-toc-on-a-new-page-after-title-page-in-rmd-to-word-doc-output/36081/4

**Comment by cderv** [comment]
This is now possible by default in last Rmarkdown version using `\newpage` or `\pagebreak` command for any format. 
See NEWS in 1.16 https://github.com/rstudio/rmarkdown/blob/master/NEWS.md#rmarkdown-116

**Comment by abubelinha** [comment]
> This is now possible by default in last Rmarkdown version using `\newpage` or `\pagebreak` command for any format.
> See NEWS in 1.16 https://github.com/rstudio/rmarkdown/blob/master/NEWS.md#rmarkdown-116
> maybe add some recipes from the vignette in this book.

Thanks @cderv 
I would like to try this ASAP.
I ran `install.packages("rmarkdown")` but my `sessionInfo()` still says I have rmarkdown_1.13
Is there some other way to update it to 1.16?

**Comment by cderv** [comment]
Version in CRAN is `2.1` now : https://cran.r-project.org/web/packages/rmarkdown/index.html
so `install.packages("rmarkdown")` should install it. You can uninstall previous version if you want o be sure with `remove.packages("rmarkdown")`. 
If you have issue, please got to RStudio Community https://community.rstudio.com/latest to ask there to get help on how to install R packages. This is a better place than this repo. Thank you !
