### ISSUE TITLE
How to change knitr options at rendering ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#158]
Not sure it is well known, even if it is in the doc but you can change knitr options with `knitr.package.<option>` in `options` like with `options(knitr.package.progress = FALSE)`

This could be very useful for changing something default at rendering, setting such an option before `render()` i.e in `_travis.yml`

```sh
script:
- Rscript -e 'options(knitr.package.progress = FALSE);bookdown::render_book("index.Rmd")'
```

It will work only if this options is not override inside the project. 

I put this here for the idea. We'll see what we'll do because I does not always work as I expected.

### Reference

* https://github.com/yihui/knitr/blob/3def2022bf8dcc634d3abbc2e3d1b6bae0cf0666/R/defaults.R#L179
* https://www.rdocumentation.org/packages/knitr/versions/1.21/topics/opts_knit

**Comment by dr-harper** [comment]
>  We'll see what we'll do because I does not always work as I expected.

Could you clarify what doesn't always work as expected?

I think this will fit in nicely with a section that I just started about creating custom render functions https://github.com/dr-harper/rmarkdown-cookbook/blob/master/book/09-workflow/custom-render-functions.Rmd. This section could ultimately build into a "scripting R Markdown" chapter or something like this.

**Comment by cderv** [comment]
I tried with the progress option as above for a bookdown and I am not sure this was taken into account properly. I believe this is a knitr feature at the beginning and maybe rmarkdown covers it. We need to check that this works as expected in a few examples and in the code. This is also something I can do. 

This could also be added to a part about customizing rmarkdown behavior. There are a lot of options stuff, including knitr hooks and all. I believe we could structure a part on how to change default behavior. I see that way for the user 
• understand what Rmarkdown is about at the bottom (generic stuff the definitive guide left in the side) 
• what rmarkdown could do natively (low advanced stuff)
• how you could get further by tweaking the behavior (high advanced stuff)
• workflow with rmarkdown : how to script and get things done non-interactively. 

This is a structure I had in mind to fit with the story I wanted to tell. 😊
