### ISSUE TITLE
How to use another format in bookdown::html_document2

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#159]
`Bookdown::html_document2()` has a `base_format` argument than can be used to changed the base format and use for example `prettydoc::html_pretty` 

```yaml
---
output:
    bookdown::html_document2:
        base_format: prettydoc::html_pretty
---
```

**Comment by dr-harper** [comment]
I feel this will fit in nicely to a small section about the benefits of bookdown (cross-referencing etc.) and explain to readers why they might want to consider doing this. As it is already mentioned in the bookdown book [here](https://bookdown.org/yihui/bookdown/a-single-document.html), I would want to make sure we add some value.

**Comment by cderv** [comment]
I think that some value can be added from the definitive guide by adding recipes as examples. I find that some features are mentioned in the guide but not always with an example showing the use or the integration with other feature. 
This is one of them. I need to find the example I encountered.

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/figure-number.html
