### ISSUE TITLE
Metadata bock can be defined also in the document and not just header

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#168]
From this question https://community.rstudio.com/t/use-r-object-in-title-of-flexdashboard/35847

I think it could be interesting to document this trick: Pandoc allow to define YAML metadata block anywhere in the document. (see [PANDOC MANUAL](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block))

So this works

````
---
output: html_document
---

```{r setup, include=FALSE}
my_title <- "I am the title"
```
---
title: '`r my_title`'
---

Test R Markdown HTML
````

Rules: First define variable is used if several.

It is not sure Rmarkdown fully consider this feature (see the [investigation in community answser](and this investigation https://community.rstudio.com/t/use-r-object-in-title-of-flexdashboard/35847/2)) but I guess it will be better by the time of this book.

**Comment by RLesur** [comment]
For the record, here is an application https://github.com/rstudio/pagedown/issues/133#issuecomment-524057353

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/dynamic-yaml.html
