### ISSUE TITLE
How to use lua filters in pandoc

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#170]
It is really easy to use lua filter with pandoc in Rmarkdown and get really advanced feature. 

See one example in my answer in this [rstudio community  post](https://community.rstudio.com/t/starting-toc-on-a-new-page-after-title-page-in-rmd-to-word-doc-output/36081/9?u=cderv) to add a pagebreak feature in any rmarkdown output that uses pandoc.

Mention also 
* some example of lua filter : https://github.com/pandoc/lua-filters
* the doc: https://pandoc.org/lua-filters.html
* and real usage in pagedown: [lua script](https://github.com/rstudio/pagedown/tree/master/inst/resources/lua) and [how it is used](https://github.com/rstudio/pagedown/blob/eb7168d6c76a8eb1b3a79b2849e0e2c48cd2bc62/R/paged.R#L30)

This is related to advanced pandoc use: #169

**Comment by RLesur** [comment]
I don't know if your goal is to write a chapter on Pandoc filters (or just on Pandoc lua filters) but the [**pandocfilters** package](https://cran.r-project.org/package=pandocfilters) might also be mentioned. It can be useful for writing Pandoc filters with R (not lua).
