### ISSUE TITLE
Some tips and conventions on authoring the book (for co-authors of this book)

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#172]
I just finished reading the current draft. I think I have to remind you of a boring yet important task: since the book is meant to be printed with a relatively small page width, we will have to make sure the images are clearly readable and the verbatim examples won't reach the page margin. For example, the font size in [Figure 4.1](https://dr-harper.github.io/rmarkdown-cookbook/crossRef.html) is way too small:

![](https://dr-harper.github.io/rmarkdown-cookbook/images/crossReferencing.png)

(In fact, this particular figure would be better if it has a frame, otherwise it can confusing to readers because they may not be able to tell the difference between the text in the book and the text in the figure. When the image doesn't have a clear border, I'll manually add one, such as Figure 6.1 in the R Markdown book: https://bookdown.org/yihui/rmarkdown/tufte-handouts.html. The ImageMagick command I used was `convert INPUT -shave 1x1 -bordercolor black -border 1 OUTPUT`.)

And the example text in Section 11.2.1 is too wide:

```
# About

This analysis was written in the R programming language [@R-base]. The report was generated using **rmarkdown** [@R-markdown] and **knitr** [@R-knitr].
```

We need to try our best to keep the line width under 70 characters. Sometimes it is hard to fit even one extra character: https://github.com/rstudio/blogdown/pull/399

The same issue exists in tables. In general, try your very best to keep the text short in tables, e.g.

- https://bookdown.org/yihui/blogdown/global-options.html
- https://bookdown.org/yihui/blogdown/more-global-options.html

It is not trivially simple to decide the best column widths to wrap long text. I have used extremely ugly hacks ([that you probably don't want to see](https://github.com/rstudio/rmarkdown-book/blob/612703943c676ad6f2572c1568b6cd61f5970ab6/index.Rmd#L40-L43)) to fix [certain tables](https://bookdown.org/yihui/rmarkdown/htmlwidgets-size.html#tab:sizing-policy) in my previous books.

I'll work on the PDF output next (with the Chapman & Hall style), and will have a better idea which elements need to be fixed.

BTW, for optimizing images, to keep the repo lean in file size, I wish you could optimize them locally before pushing to Github (then rely on a Github bot to optimize them and send pull requests, which will inflate the size of the repo). I have a helper function `xfun::optipng()` to do that if you have installed `optipng`. I kind of have an OCD on this. All images in my previous books were heavily optimized before I commit them because I don't like version control binary files in general. I not only run `optipng` but also use https://imagecompressor.com to further optimize them as much as possible, to the point where I feel the loss of quality is noticeable.

**Comment by yihui** [comment]
Currently the capitalization of chapter/section titles is very inconsistent. Usually I capitalize all words in chapter titles, but only the first word in section titles.

**Comment by atusy** [comment]
I give you a tip to automatically add borders to figures by using a chunk option `fig.process`

````
```{r}
add_border <- function(x) {
  i <- imager::load.image(x)
  i[imager::px.borders(i)] <- 0
  imager::save.image(i, x)
  x
}
```

```{r, fig.process=add_border}
plot(1:5, 1:5)
```
````

**Comment by yihui** [comment]
@atusy That's very neat. Thank you!
