### ISSUE TITLE
Holtz Yan's R Markdown tips

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#173]
I just discovered @holtzy's repo yesterday: https://github.com/holtzy/Pimp-my-rmd It is so awesome! We should borrow some tips to this book if we can get his permission.

**Comment by cderv** [comment]
Oh nice I did know this one ! It’s Great !

**Comment by holtzy** [comment]
I just discovered this issue. I would be honored if you used any of the little tips I've shared in this doc! Thanks for your work!
