### ISSUE TITLE
Recipes about code chunk option to use external scripts (R, SQL, ...) as content for a chunk

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#174]
From a question on community.rstudio.com
https://community.rstudio.com/t/how-to-write-r-script-into-rmd-as-functioning-code-chunk/37453/5

Add a small demo of the code chunk option to show how to use it.

### Related SO questions

* https://stackoverflow.com/questions/52397430/include-code-from-an-external-r-script-run-in-display-both-code-and-output

**Comment by cderv** [comment]
Related to #112

**Comment by cderv** [comment]
In fact, `code` chunk is mentioned already in the `cat` engine part. It kind of hidden in it as a trick but present. However, I began to wrote a new part on this before seeing it 😟 but I am not sure it is necessary to duplicate... 

Also @yihui, I wonder if you prefer to review the all existing book before I began to help by writing some pieces ? I wonder if it would be more efficient in order to have the structure of the book you want before trying to help. 🤔  You may also prefer to write alone right now 😉

**Comment by yihui** [comment]
I have been reviewing and revising the parts that you two have written. I feel I'll need one more month to finish that. Before then, I probably won't have time to review new pull requests. Thank you!

**Comment by cderv** [comment]
My intuition was correct then. we’ll see in one month.

**Comment by cderv** [comment]
Addition in this in 26fbc5b

**Comment by cderv** [comment]
See also this question on community where I build an example on 
How to use external SQL script to fill SQL chunk while taking advantage of SQL knit engine (i.e `output.var`)
https://community.rstudio.com/t/rmd-file-with-embedded-sql-chunk-possible-to-move-the-sql-to-external-file-then-source/49651/3

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/option-code.html
