### ISSUE TITLE
Add and customize table of content

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#18]
Questions in SO about adding a toc. 

However, this is cover in the guide
* For HTML : https://bookdown.org/yihui/rmarkdown/html-document.html#table-of-contents
* For PDF: https://bookdown.org/yihui/rmarkdown/pdf-document.html#table-of-contents-1
* For Word: not clearly mentionned, but listed in the [cheatsheet ](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)

Not sure how the book will be organized but if not by output, a recipe could centralized the question "How to add a toc?" for the various output.

 ## Related SO question
- [ ] https://stackoverflow.com/questions/23957278/how-to-add-table-of-contents-in-rmarkdown
- [ ] https://stackoverflow.com/questions/29997263/linked-table-of-contents-toc-in-md-using-rmarkdown

**Comment by cderv** [comment]
I think this is already covered in the definitive guide, with already a recipe covered in https://github.com/yihui/rmarkdown-cookbook/issues/184

I think we can close. @yihui are you ok?

**Comment by yihui** [comment]
Yes. Thanks!
