### ISSUE TITLE
Ideas for the book cover

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#180]
Although it is still early to talk about the book cover, but this wonderful artwork just came to my mind again: https://github.com/allisonhorst/stats-illustrations/blob/master/rstats-artwork/rmarkdown_wizards.png We might ask Allison for help with designing the book cover once the content is finished.

**Comment by cderv** [comment]
Oh yes this artwork is awesome ! Great Idea to ask Allison !

**Comment by yihui** [comment]
@cderv @emilyriederer Our publisher allows us to pick an image from shutterstock.com. I wonder if you prefer doing that, or having Allison help us (I reached out to her a few months ago and she was willing to help). I certainly love the wizard cartoon, but I'm concerned that after we use it as our cover image, it'd be "owned" by this particular book. I don't want to build a specific connection between the two. I guess Allison will do a much better job than shutterstock.com, since she definitely understands R Markdown better, but I'm a little worried about how much time it would take for her to design another cartoon for R Markdown.

**Comment by emilyriederer** [comment]
I definitely also love the wizard cartoon, but you make a good point about now wanting it to be "owned".  A couple of options I think of are:

1.  If Allison made a "simplified" version of this drawing, perhaps this preserves the uniqueness of the original work while still putting it to good use here. For example, the image right now is  potentially a bit "wide" for the book cover.  Perhaps she could take out the "RMarkdown" text and bookshelf but keep the wizards and the rendering process? 

2. Another graphic I remember really liking from the R community is Thomas' from the `blogdown` sticker contest. Perhaps there is some concept related to this that might make a good cover? 

![image](https://user-images.githubusercontent.com/19798371/86420711-0d76d380-bc9d-11ea-8fed-85e83865d88a.png)

3. I don't have any stock photo ideas off the bat, but I'm happy to explore options on Shutterstock more if that's the better path

**Comment by cderv** [comment]
>  I guess Allison will do a much better job than shutterstock.com

I agree ! 

>   but I'm a little worried about how much time it would take for her to design another cartoon for R Markdown.

We should asked her. Maybe she has one in stock from when she created the one we know ? 

Idea: The Definitive Guide book cover was a patchwork of different output format 
![image](https://user-images.githubusercontent.com/6791940/86436169-0635e100-bd02-11ea-957f-6ce3c98fa87f.png)

Maybe Alisson could revisit that her way, by adding some element for her other drawing ? But it could be an idea for a second edition of The definitive guide.... 🤔 

Also another idea: 
The cover could be a patchwork for different package logos we mention in the book ? Knitr, rmarkdwn, bookdown, blogdown, ... 
Maybe to simple.

@emilyriederer will you contact Alisson ?

**Comment by emilyriederer** [comment]
Will do, @cderv !

**Comment by allisonhorst** [comment]
Hi everybody, thanks for considering me for some cover artwork! 

A couple options: 

- Option 1: I'd love to see the R Markdown wizards on there in some form, possibly simplified & reformatted to better fit on a book cover layout. Honestly I'm happy if you want to use the existing illustration, but it should probably be updated a bit to fit the cover space (I can do that pretty quickly) 
- Option 2: Have little R Markdown wizards doing different tasks, then placed over & around an R...like on the Definitive Guide but it's R monsters knitting, or stirring the yaml, or whatever, all around the R, which I think would be awesome

Also open to other ideas!

**Comment by emilyriederer** [comment]
Thank you so much @allisonhorst ! Either of those sound fantastic to me. Let's hope people *do* judge this book by its cover 😄

**Comment by yihui** [comment]
@allisonhorst How about Option 1? Because it sounds easier to you, and everybody loves it. I think they will also love the simplified version. Thank you!

**Comment by allisonhorst** [comment]
Sounds good, I'll put together a simplified version & send it over!

**Comment by allisonhorst** [comment]
OK here is a version of the wizards art without the cabinet of ingredients. Can you let me know what size (aspect ratio) the art should fill? Then I can update this to best fill the space. 

Also, the text anywhere is really easy to change. For example, what do you want on the "list" (or that can be removed?). 

Open to all suggestions & will be ready to edit this quickly. -Allison

![rmarkdown_cover](https://user-images.githubusercontent.com/25372780/88212937-e57bef80-cc0c-11ea-8ff0-6385741a8f55.png)

**Comment by cderv** [comment]
Wow this is awesome ! It is perfect for a Cookbook ! Thank you !

**Comment by RLesur** [comment]
Sorry for hijacking this convo but I've a suggestion: maybe the knitr wizard could use a hook?

**Comment by cderv** [comment]
> maybe the knitr wizard could use a hook?

Great Idea ! Maybe _4. (Hook magic)_ instead of just _4. (magic) ?_

**Comment by emilyriederer** [comment]
@allisonhorst - thank you so much, this is brilliant!! And @RLesur @cderv, love the hook idea 😆

**Comment by yihui** [comment]
@allisonhorst I just asked our publisher about the aspect ratio. From my past experience, the aspect ratio of the current design should be fine. I'm not sure if the font size is large enough to be readable. I have also asked them about this issue, and will let you once I hear back from them. Thank you!

**Comment by allisonhorst** [comment]
The wand can definitely be a hook! Can someone share a picture of the type of hook that would making sense here? I don't knit or crochet but I'm guessing there is a correct one for this illustration :) Yeah I agree, all of the font is probably too small for a book cover. I think it stands on its own without any text, here's what it looks like text removed (also moved the left wizard a bit closer...it felt spread too thin in the previous version). 
![rmarkdown_cookbook_cover_v2](https://user-images.githubusercontent.com/25372780/88241044-d3667500-cc3d-11ea-87e4-8dd39e9bf488.jpg)

**Comment by allisonhorst** [comment]
Or there could just be the major text pieces (R Markdown, knitr, pandoc?) but none of the smaller ones?

**Comment by yihui** [comment]
Personally I don't mind if the font is too small, and I prefer including the text even if it's not very readable.

**Comment by RLesur** [comment]
> Can someone share a picture of the type of hook that would making sense here?

When I saw the green wizard's wand, it made me think of a [dreadlock hook](https://www.google.com/search?tbm=isch&q=dreadlock+hook) :smile: 

Here's a couple of dreadlock hooks I've found on the web:

![dreadlocks_hooks](https://user-images.githubusercontent.com/19177171/88265294-8500b700-cccd-11ea-8e55-8047a336a5f4.jpg)

**Comment by cderv** [comment]
> Personally I don't mind if the font is too small, and I prefer including the text even if it's not very readable.

I agreee with yihui. I prefer the version with the text

> Can someone share a picture of the type of hook that would making sense here?

I was more thinking of crochet hook myself

![image](https://user-images.githubusercontent.com/6791940/88270192-8afa9600-ccd5-11ea-944d-d172d44bbc65.png)

![image](https://user-images.githubusercontent.com/6791940/88270260-a2d21a00-ccd5-11ea-80e1-8d57ac65bc58.png)

![image](https://user-images.githubusercontent.com/6791940/88270296-b4b3bd00-ccd5-11ea-9eb6-02d6013cb9ae.png)

**Comment by RLesur** [comment]
> I was more thinking of crochet hook myself

A crochet hook makes more sense for knitr :+1:

**Comment by yihui** [comment]
The hook might be too subtle for people to recognize. It probably won't make much difference if it is a wand or hook given the size of the image on the cover.

**Comment by yihui** [comment]
@allisonhorst Here is the response from our publisher (which I don't completely understand):

> Looks pretty good. Can they provide it with layers active so I can easily get it off the white background (unless you want a white box around it)? Those vapors coming from the cauldron will be next to impossible to lift off the white if the image comes flattened.

If you don't mind, I can have them email you directly.

**Comment by emilyriederer** [comment]
One last thought (but please feel free to disregard if it is extra work!), one thing I adore about the drawing is the subtle labeling of `.Rmd` on the pipe between the first two cauldrons and `.md` after the second. It's so subtle and whimsical but contains so much information about how `rmarkdown` actually works. Sadly, this will definitely be too small to see. 

Do you think it would work to put letters on a few of the bubbles in the first cauldron like "R" "py" "sql" for the different language engines? Then perhaps a bubble in the second could just say "md". 

Obviously, that's very trivial in the grand scheme of things so not important at all. Thank you again so much for making this!

**Comment by allisonhorst** [comment]
Hi @emilyriederer I just saw this comment, I'm happy to send over a version with the .Rmd & .md if that's still of interest!

**Comment by emilyriederer** [comment]
Thanks @allisonhorst , but no need -- I think it's perfect as-is!
