### ISSUE TITLE
Packages for drawing diagrams

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#185]
Just saw this one today: https://github.com/javierluraschi/nomnoml

Of course, there is also https://github.com/rich-iannone/DiagrammeR

**Comment by cderv** [comment]
There is also ggdag https://github.com/malcolmbarrett/ggdag working with daggity https://cran.r-project.org/web/packages/dagitty/index.html

But nomnoml knitr engine is so powerful with Rmarkdown ! Very nice package !

**Comment by atusy** [comment]
Yes, nomnoml sounds nice.

Personally, I love https://github.com/rkrug/plantuml.
It works on Linux, but maybe not on Windows as far as I tried.
