### ISSUE TITLE
How to customize data.frame output printing for all chunk through df_print ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#186]
Rmarkdown output formats have a `df_print` argument that could be used to format every data.frame output the same throughout the document. 

There are some useful tips to know: 

- [ ] some format have hard-coded value like "paged" for `html_notebook`
- [ ] When choosing `df_print = kable`, one can use `kable-scroll` to make scrollable kable tables. 
- [ ] To fully customize the format, a function can be passed to `df_print` though yaml or format function. This can be used for a custom printing function or to pass some options
- [ ] Options for paged table output can also be passed through R options or knitr option (in a setup chunk for examples) 

# related questions

- https://github.com/rstudio/rmarkdown/issues/1748
- https://stackoverflow.com/questions/40893742/r-markdown-df-print-options
- https://stackoverflow.com/questions/44443765/pass-df-print-an-arbitrary-function-when-knitting-in-rstudio

**Comment by atusy** [comment]
If one wants to define a complex function for `df_print`, `registerS3method` will help.

````
```{r, include = FALSE}
registerS3method("knit_print", "data.frame", function(x, ...) {
  knitr::knit_print(knitr::kable(x), ...)
})
```
````

Simply assigning `knit_print.data.frame` will  also help if `options(rmarkdown.df_print = FALSE)` is set before loading the `rmarkdown` package (cf. https://github.com/rstudio/rmarkdown/blob/master/R/zzz.R#L1-L9).

```
knit_print.data.frame <- function(x, ...) knitr::knit_print(knitr::kable(x), ...)
```
