### ISSUE TITLE
Rendering a pdf with multi-column layout does not work as documented

### ISSUE THREAD

**Issue by rmoor** [yihui/rmarkdown-cookbook#188]
I am trying to follow the multi-column layout section in the Markdown Cookbook to render a two-column pdf. 
As instructed, I created the columns.tex file and saved it in my working directory. And copy the exact same code in the book (only output pdf). Then I got the error that columns.tex is not found. 

**File columns.tex not found in resource path
Error: pandoc document conversion failed with error 99
Execution halted**

Maybe I put the file in the wrong location. I wonder how to make markdown find the file.

Many thanks

**Comment by rmoor** [comment]
Update. 
I solved the "cann't find issue" by setting the working directory properly. But the output pdf is still one column. 

Here is my code (same with Markdown Cookbook):

---
output:
  pdf_document: 
    keep_tex: true
    includes:
      in_header: columns.tex

---
# Two columns

Below is a Div containing three child Divs side by side. The Div
in the middle is empty, just to add more space between the left
and right Divs.

:::::: {.columns}

::: {.column width="55%"}
```{r, echo=FALSE, fig.width=5, fig.height=4}
par(mar = c(4, 4, .2, .1))
plot(cars, pch = 19)
```
:::

::: {.column width="5%"}
\ 

:::

::: {.column width="40%"}
The figure on the left-hand side shows the `cars` data.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
in reprehenderit in voluptate velit esse cillum dolore eu fugiat
nulla pariatur.
:::
::::::

Then the resulting pdf is still one column. Is there anything wrong with my code?
<img width="615" alt="Screen Shot 2020-02-28 at 9 19 34 PM" src="https://user-images.githubusercontent.com/44073162/75584547-4ba28300-5a70-11ea-9a24-bff3f0b9253d.png">

**Comment by cderv** [comment]
Hi @rmoor, 

Thanks for the report. it seems there is an issue with pdf_output in this example... 🤔 I don't find why, but yes this does not seems to work. 

`fenced_divs` feature of pandoc does not seem to be handle by default by pandoc for tex output. 
Here is a reprex. 
``` r
dir.create(tmp_dir <- tempfile())
xfun::in_dir(tmp_dir, {
  xfun::write_utf8(c(
    "---",
    "title: MWE",
    "---",
    "",
    "::: Warning ::::::",
    "This is a warning.",
    "",
    "::: Danger",
    "This is a warning within a warning.",
    ":::",
    "::::::::::::::::::"
  ), "test.Rmd")
  res <- rmarkdown::render("test.Rmd", rmarkdown::latex_document(), envir = new.env())
  message("content of ", basename(res), " below: ")
  cat(tail(readLines(res), 20), sep = "\n")
})
#> processing file: test.Rmd
#> output file: test.knit.md
#> "C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output test.tex --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --lua-filter "C:/Users/chris/Documents/R/win-library/3.6/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/Users/chris/Documents/R/win-library/3.6/rmarkdown/rmd/lua/latex-div.lua" --variable "geometry:margin=1in"
#> 
#> Output created: test.tex
#> content of test.tex below:
#> \makeatletter
#> \def\fps@figure{htbp}
#> \makeatother
#> \setlength{\emergencystretch}{3em} % prevent overfull lines
#> \providecommand{\tightlist}{%
#>   \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
#> \setcounter{secnumdepth}{-\maxdimen} % remove section numbering
#> 
#> \title{MWE}
#> \author{}
#> \date{\vspace{-2.5em}}
#> 
#> \begin{document}
#> \maketitle
#> 
#> This is a warning.
#> 
#> This is a warning within a warning.
#> 
#> \end{document}
unlink(tmp_dir)
```

<sup>Created on 2020-02-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I need to understand why this was wrote, if this is really a missing feature in pandoc that we thought was there. There may be an option to activate that we missed. 

Thanks a lot for the report.

**Comment by rmoor** [comment]
Thank you for looking into this! Please feel free to keep me posted on the feedback!

**Comment by cderv** [comment]
@yihui, did I missed something here ? How did you make it worked ? 

I t
````r
---
title: "MWE"
output:
  pdf_document:
    keep_tex: yes
---

:::::::::::::: {.columns}
::: {.column width="40%"}
contents...
:::
::: {.column width="60%"}
contents...
:::
::::::::::::::
````
gives no `\begin{column}` in the tex file

```tex
\begin{document}
\maketitle

contents\ldots{}

contents\ldots{}

\end{document}
```

This [could maybe done with lua filter](https://tex.stackexchange.com/questions/525924/with-pandoc-how-to-apply-a-style-to-a-fenced-div-block), but does not seems to be by default in pandoc

Did I missed something ?

**Comment by cderv** [comment]
Oups my bad. I forgot ! 
Thanks @RLesur for reminding me of the lua filters added in rmarkdown that offers this features: https://github.com/rstudio/rmarkdown/commit/cecd812743826989b539a7b0fcb1b8c08f09c05d

I'll look into it, why it does not work as expected, but @rmoor you need at least rmarkdown 1.16 and pandoc 2.0 for this.

**Comment by cderv** [comment]
Oh It was quick... it seems that for the lua filters to work there should be `data-latex=""` added otherwise it is not activated. 

````r
---
title: "MWE"
output:
  latex_document: default
---

:::::::::::::: {.columns data-latex=""}
::: {.column width="40%" data-latex=""}
contents...
:::
::: {.column width="60%" data-latex=""}
contents...
:::
::::::::::::::
````
results in the correct tex output

<details><summary> See tex output </summary>

```tex
\begin{document}
\maketitle

\begin{columns}

\begin{column}

contents\ldots{}

\end{column}

\begin{column}

contents\ldots{}

\end{column}

\end{columns}

\end{document}
```
</details>

I think there could be something done about that to not require this and be more multi-format. 🤔

**Comment by rmoor** [comment]
Thank @cderv for the quick response!!

My rmarkdown and pandoc are the latest versions. I can get the same tex output with you using the code above. 

However, when I tried to kintr the code below, I was left with some errors. Here my code and error messages

````
---
title: "MWE"
output: 
    pdf_document: 
      keep_tex: true
      includes:
        in_header: columns.tex
---

:::::::::::::: {.columns data-latex=""}
::: {.column width="40%" data-latex=""}
contents...
:::
::: {.column width="60%" data-latex=""}
contents...
:::
::::::::::::::
````

And it returns:

> processing file: Untitled.Rmd
output file: Untitled.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS Untitled.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Untitled.tex --self-contained --highlight-style tango --pdf-engine pdflatex --include-in-header columns.tex --variable graphics --lua-filter /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmd/lua/latex-div.lua --variable 'geometry:margin=1in' 
! Paragraph ended before \@iiiminipage was complete.
<to be read again> 
                   \par 
l.89 

Error: LaTeX failed to compile Untitled.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Untitled.log for more info.
Execution halted


Did I miss anything?

**Comment by cderv** [comment]
No you did not missed anything. I did not said it was fixed yet... ☺️ still looking into it.

**Comment by cderv** [comment]
Just to continue keep track on my finding :
keeping on digging, I think I found why I thought the behavior has changed. Since https://github.com/jgm/pandoc/commit/548ffa38c3b7850334f80d037521bd30ee171eee (and pandoc 2.7.3, pandoc does not create anymore environment for columns divs, as it does with Latex. That is why I get nothing in resulting tex file. Only solution is using a Lua filter to add those.

**Comment by cderv** [comment]
@rmoor it seems some options are indeed required for the `colums.tex` to work and make its magic. 

I got this to work by adding the correct options using `data-latex=` attributes for this special feature of rmarkdown. 

````r
---
output:
  pdf_document: 
    keep_tex: true
    includes:
      in_header: columns.tex
  beamer_presentation: default
  html_document: 
    css: columns.css
---

# Two columns

Below is a Div containing three child Divs side by side. The Div
in the middle is empty, just to add more space between the left
and right Divs.

:::::: {.columns}

::: {.column width="55%" data-latex="{0.55\textwidth}"}
```{r, echo=FALSE, fig.width=5, fig.height=4}
par(mar = c(4, 4, .2, .1))
plot(cars, pch = 19)
```
:::

::: {.column width="5%" data-latex="{0.05\textwidth}"}
\ 
<!-- an empty Div (with a whitespace), serving as
a column separator -->
:::

::: {.column width="40%" data-latex="{0.4\textwidth}"}
The figure on the left-hand side shows the `cars` data.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
in reprehenderit in voluptate velit esse cillum dolore eu fugiat
nulla pariatur.
:::
::::::
````

It got me thinking about this feature, so I don't know what is the best way yet to do this. `width=` is required for html output here, and `data-latex=` for pdf output. `columns.tex` defines how to deal with `column` and `columns` environment created by rmarkdown lua filter. 

This example can know be multi format I guess. 

Thanks again for the report - there is definitely something to improve here (in the book or one the 📦 )

**Comment by rmoor** [comment]
@cderv Thanks sooo much!! This is awesome! It worked on my side as well. 

One minor question: seems the `width = ` and `data-latex=` have to coexist in the bracket even if I don't need html output, right? I tried without `width = ` for pdf alone, then the magic doesn't work...

**Comment by cderv** [comment]
> One minor question: seems the width = and data-latex= have to coexist in the bracket even if I don't need html output, right? I tried without width = for pdf alone, then the magic doesn't work...

it should work. `width=` is not used with pdf output, only html. `data-latex=` is a rmarkdown feature used only for pdf and passed as option in latex environment.

<details><summary> This works for me </summary>

````
---
output:
  pdf_document: 
    keep_tex: true
    includes:
      in_header: columns.tex
---

# Two columns

Below is a Div containing three child Divs side by side. The Div
in the middle is empty, just to add more space between the left
and right Divs.

:::::: {.columns}

::: {.column data-latex="{0.55\textwidth}"}
```{r, echo=FALSE, fig.width=5, fig.height=4}
par(mar = c(4, 4, .2, .1))
plot(cars, pch = 19)
```
:::

::: {.column data-latex="{0.05\textwidth}"}
\ 
<!-- an empty Div (with a whitespace), serving as
a column separator -->
:::

::: {.column data-latex="{0.4\textwidth}"}
The figure on the left-hand side shows the `cars` data.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
in reprehenderit in voluptate velit esse cillum dolore eu fugiat
nulla pariatur.
:::

::::::
````

</details>

**Comment by rmoor** [comment]
Got it! It’s working now. Previously I took out the “.column” as well, which was why it did not work before. Appreciate it!

**Comment by yihui** [comment]
Many thanks @rmoor for the report! I was using Pandoc 2.3.1 when I wrote this section. Apparently it no longer works with Pandoc after v2.7.3. I just updated the example, and also made the necessary changes in the **rmarkdown** package (`remotes::install_github('rstudio/rmarkdown')`), thanks to the careful investigation and code contributed by @cderv!

**Comment by yihui** [comment]
Please note that I have just renamed the environments `columns` to `cols`, and `column` to `col` in 4a725c0be46739a5abfff544c5add09f3d0cbae1. Reason: https://github.com/yihui/rmarkdown-cookbook/blob/4a725c0be46739a5abfff544c5add09f3d0cbae1/05-formatting.Rmd#L359
