### ISSUE TITLE
Different results using knit button and rmarkdown::render in generating two-column layout html

### ISSUE THREAD

**Issue by rmoor** [yihui/rmarkdown-cookbook#189]
I try to reproduce the two-column layout using the code in the rmarkdown cookbook. The code is exactly the same as in the example. Something strange occurs: clicking knit button gave me the right two-column layout html report, while using rmarkdown::render still gave me the single-column layout. I wonder if the code in the example in the book is not cooperating with render. Is there a way to render two-column layout in the places I want rather than all throughout?

Many thanks!

**Comment by rmoor** [comment]
Here is the code I used (flexbox in css)

---
output: html_document
---

:::: {style="display: flex;"}

::: {}
Here is the **first** Div.

```{r}
str(iris)
```
:::

::: {}
And this block will be put on the right:

```{r}
plot(iris[, -5])
```
:::

::::

**Comment by cderv** [comment]
This is working fine on my side. The results are identical from the command line and the knit button. 
The html should be the same, you can open the html file and see the difference if any.

Also to format you issue next time, please follow advices here: 
https://yihui.org/issue/#please-format-your-issue-correctly

Also, about 
> Is there a way to render two-column layout in the places I want rather than all throughout?

You can do any css you want regarding this css flex feature and based on the example showing pandoc feature. You should ask on RStudio Community or Stackoverflow if you want to get feedback and idea from others. This repo's issue tracker is for topic and idea for the book, and also required clarifications.

So I'll close for now, but please reopen if you identify real difference in html files, and the examples is not clear enough. I don't see what could happen as knitr button call rmarkdown render function, in a new process, but I may have missed something. 

Thank you !

**Comment by rmoor** [comment]
Thank you so much! I’ll follow the format the next time! And will work on the code:)

Best
