### ISSUE TITLE
How to do a two-column layout ?

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#19]
A specific question we find on SO, but that I can relate to because some colleagues often ask. More generally is how to customize the layout of your output. Maybe too broad or an idea for a specific chapter in the book. 

## Related SO questions:
* About slidify but gives solution for several formats: https://stackoverflow.com/questions/20847371/two-column-layouts-in-rstudio-presentations-slidify-pandoc
* About beamer: https://stackoverflow.com/questions/15142134/slides-with-columns-in-pandoc
* About ioslide https://stackoverflow.com/questions/22871611/how-can-i-fix-column-breaks-in-an-rmarkdown-ioslides-presentation
* https://stackoverflow.com/questions/31603577/two-column-layout-with-markdown

**Comment by cderv** [comment]
`rticles` 📦 has also two columns layout latex template I think.

**Comment by cderv** [comment]
Related : https://stackoverflow.com/questions/28000062/tables-and-figures-side-by-side-in-knitr-or-rmarkdown-beamer

**Comment by cderv** [comment]
https://stackoverflow.com/questions/19237190/2-column-report-in-r-markdown-render-html-aside-data-frame

**Comment by cderv** [comment]
This is now added in https://bookdown.org/yihui/rmarkdown-cookbook/multi-column-layout.html with several recipes. 

From all that was gathered above, I see two possible additions: 

## How to get full two columns document in PDF ? 

From : https://github.com/yihui/rmarkdown-cookbook/issues/19#issuecomment-431581739, https://github.com/yihui/rmarkdown-cookbook/issues/19#issuecomment-428835793 and https://github.com/yihui/rmarkdown-cookbook/issues/19#issuecomment-431580529

Something like this seems to work using `classoption: twocolumn` and `\onecolumn` or `\twocolumn` command. But not easy to tune apparently
<details><summary>Examples</summary>

````r
---
output:
  pdf_document: 
    keep_tex: true
classoption: twocolumn
---

# Using two columns

```{r, echo = FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(10), sep = "\n")
```

\onecolumn

# New chapter with only one column

```{r, echo = FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(5), sep = "\n")
```
````
</details>

This could also be a way to mention packages with those kind of twocolumn format (`pinp` and `rticles`)

You know better than me about latex, so you may be able to see if it worths mentioning.

## Using `multicol` latex package

From https://github.com/yihui/rmarkdown-cookbook/issues/19#issuecomment-426152647

It seems that `multicol` package is easier to use than the `minipage` in `column.tex`

<details><summary>See example </summary>

````r
---
output: pdf_document
header-includes:
  - \usepackage{multicol}
---

# Using two columns

\begin{multicols}{2}

```{r, echo = FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(2), sep = "\n")
```

\end{multicols}

# New chapter with only one column

```{r, echo = FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(2), sep = "\n")
```
````
giving 
![image](https://user-images.githubusercontent.com/6791940/79506726-c92d4d00-8036-11ea-8b9e-dbdebd228797.png)

</details>

maybe a simple lua filter is possible to transform `:::::: {.columns}` and `::: {.column}` into the use of `multicol` packages for pdf document.  🤔 

Again I am far from being a Tex expert, so I don't know specifically what this Tex multicol 📦 is worth.
I found about it in one of the SO answer and more in [here](https://www.overleaf.com/learn/latex/Multiple_columns) 

@yihui if you find one of the above useful addition, we can leave it open to not forget adding about these. Otherwise, we can close this issue.

**Comment by cderv** [comment]
`classoption` is now mentioned in cb82b3bfda9a7911e92d68a3d0cd3b085280a143 in the part about latex template

**Comment by yihui** [comment]
I just mentioned `\onecolumn` and `\twocolumn` in a footnote. I'll leave out the **multicol** package. Thanks!

**Comment by overbeek42** [comment]
Just updating a now dead link to the page in the rmarkdown cookbook: https://bookdown.org/yihui/rmarkdown-cookbook/multi-column.html

**Comment by yihui** [comment]
@overbeek42 Thanks! I just updated the link above.

**Comment by overbeek42** [comment]
Great. Sorry for responding to a closed issue. I later saw that this causes
you anxiety. Didn't mean to.

**Comment by yihui** [comment]
No worries! In this case, it didn't cause me any anxiety at all since it was extremely easy to deal with, and it's entirely reasonable to reply under this issue since you were pointing out a problem right inside this issue. I really appreciate that.

**Comment by overbeek42** [comment]
Glad there's no hard feelings. Happy to be of some help after you enabled
be to create amazingly crisp and neat slides to present my research!

**Comment by piiskop** [comment]
> ```r
> \begin{multicols}{2}
> 
> ```{r, echo = FALSE, results='asis'}
> cat(stringi::stri_rand_lipsum(2), sep = "\n")
> ```
> 
> \end{multicols}
> 
> # New chapter with only one column
> 
> ```{r, echo = FALSE, results='asis'}
> cat(stringi::stri_rand_lipsum(2), sep = "\n")
> ```
> ```

It does not work with verbatim code chunks though. And it is impossible to put subheadings inside `multicols`.
