### ISSUE TITLE
Embedded files in HTML output

### ISSUE THREAD

**Issue by fmmattioni** [yihui/rmarkdown-cookbook#196]
Perhaps the package I developed https://github.com/fmmattioni/downloadthis could be added to this section: https://bookdown.org/yihui/rmarkdown-cookbook/embed-file.html.

This package was inspired by [this post](https://yihui.org/en/2018/07/embed-file/) and it uses a Bootstrap 3 button from the [bsplus](https://github.com/ijlyttle/bsplus) package.

**Comment by yihui** [comment]
Added. Thank you!
