### ISSUE TITLE
Xaringan Recipe on using `fig.chunk()` 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#198]
It was intially in #13 there was the recipe of this great post https://www.garrickadenbuie.com/blog/decouple-code-and-output-in-xaringan-slides/#using-knitr-fig-chunk following one of your comment on twitter https://twitter.com/xieyihui/status/1031033538743857153

I think adding this xaringan recipe about using `fig_chunk()` could be great here 
https://bookdown.org/yihui/rmarkdown-cookbook/fig-chunk.html

**Comment by yihui** [comment]
I only mentioned that `fig_chunk()` could be used on slides, without being specific about **xaringan** (otherwise it may sound like too much self-promotion :). Thanks!
