### ISSUE TITLE
Difference between html_notebook and html_document

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#20]
Based on a question found on SO. 

I am not sure if there is a how-to or recipe to offer on this the book. However, I open the issue to be exhaustive, so that we can close the idea that are not good enough. 

However, after some though, it could be useful to have a how-to reproduce notebook feature in html document. I had the question for downloading Rmd file (`code_download  = TRUE`), or having a global button for hiding code  (`code_folding = c("none", "show", "hide")`)

## Related SO questions
* https://stackoverflow.com/questions/43820483/difference-between-r-markdown-and-r-notebook

**Comment by abalter** [comment]
I absolutely can't see any reason to use `html_document`. I haven not found any features that `html_document` has that `html_notebook` doesn't. However, the notebook format is more interactive (you can preview without knitting), and allows you to download the original markdown code which I think strongly supports reproducible science.

**Comment by cderv** [comment]
Thanks for your feedback! 

If `.nb.html` is the right format for you then that is great ! Some user may prefer to produce a `.html` document only without all the notebook feature for publishing, or sharing to others only the production and not the source content. Also `.nb.html` works in RStudio IDE as the features are tied to it, and not outside. 

Anyhow, we provide multiple format to meet everyone's need. We're glad that you are a happy user of `html_notebook`.
