### ISSUE TITLE
 建议默认不要使用 tcolorbox 宏包提供的 many 选项

### ISSUE THREAD

**Issue by XiangyunHuang** [yihui/rmarkdown-cookbook#201]
many 选项虽然提供最全的功能，同时也提供最多的宏包依赖，这时就要考虑宏包的加载顺序，几乎可以肯定地说 `\usepackage[many]{tcolorbox}` 移动到本书的导言区肯定编译不出 PDF，因为它会和 amsthm 宏包冲突，我还是建议读者需要多少用多少，想用的多自己就要多注意！

在这里完全可以不要设置选项

https://github.com/yihui/rmarkdown-cookbook/blob/e6e47d76427911e8cf3aa0427b83cc30fd34177c/08-multiformat.Rmd#L240-L247

**Comment by yihui** [comment]
好的，谢谢！
