### ISSUE TITLE
reticulate 包真的值得一提

### ISSUE THREAD

**Issue by XiangyunHuang** [yihui/rmarkdown-cookbook#205]
- 在 R 中使用 gluon https://d.cosx.org/d/419785-r-gluon
- 纯 Python 代码块绘图 https://d.cosx.org/d/421249-knitr-1-26-1-27-1-28-python

我给了一些 R 与 Python 交互的例子 

- 轻量级 numpy 模块 https://bookdown.org/xiangyun/r-pkgs/chap-reticulate.html
- 重量级 mxnet 模块 https://bookdown.org/xiangyun/r-pkgs/chap-mxnet.html

**Comment by XiangyunHuang** [comment]
已经在 R Markdown: The Definitive Guide 提到了

https://bookdown.org/yihui/rmarkdown/language-engines.html#python

**Comment by yihui** [comment]
谢谢建议！
