### ISSUE TITLE
Add citation entries

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#208]
Most R packages are cited only through links. We need to add formal citations.

**Comment by emilyriederer** [comment]
For this item, do you prefer to cite a package the first time it is mentioned or each time? I'm assuming the latter but just wanted to check. Thanks!

**Comment by yihui** [comment]
For packages that are very frequently mentioned in this book, there's no point of citing them every time (e.g. **rmarkdown**, **knitr**). For other packages that are mentioned once or twice, I think it's fine to cite them whenever they are mentioned. It really depends on whether you think the reader needs a reminder about the package. For example, if a package has just been cited in the beginning of a section, you probably don't need to cite it again in the end of this section.

BTW, I assume you know that the package citation entries are dynamically generated. If not, they are generated here: https://github.com/yihui/rmarkdown-cookbook/blob/master/18-references.Rmd

**Comment by emilyriederer** [comment]
Thanks -- that all makes sense. Will do! 

(Yes - thanks! I did see that, but I always appreciate your mentioning just in case. I can also refer back to the [book itself](https://bookdown.org/yihui/rmarkdown-cookbook/write-bib.html) for any clarification! 😄 )

**Comment by yihui** [comment]
One more thing: if a package is only available on Github (and not CRAN), I think it's fine to only use links.

**Comment by emilyriederer** [comment]
Sorry for so many questions on this one! 

1. Do LaTeX or JavaScript packages need to be cited in any way or just R packages?
2. For packages that are on CRAN shall I remove the GitHub link when putting in the citation or keep both? For example, should:

> the **spelling** package (https://github.com/ropensci/spelling)

become

> the **spelling** package (https://github.com/ropensci/spelling) [@R-spelling]

or this

> the **spelling** package [@R-spelling]

Thank you!

**Comment by yihui** [comment]
No worries.

1. Only cite R packages (only because it's convenient).
2. You can remove the link, and only keep `[@R-pkg]`.
