### ISSUE TITLE
Adjust figures to fit PDF pages

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#210]

**Comment by yihui** [comment]
One reviewer mentioned for this section https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html that:

> Figure 12.1 and 12.2 would be best placed right next to each other, so that the difference in crop can be seen.

Let's see if they could be moved closer to each other after the content is finalized (don't try before then, because floats are kind of unpredictable).

**Comment by yihui** [comment]
One reviewer mentioned:

> Figure 10.3 should be positioned directly after the following code block at the end of page 154.
> 
> ```
> fit <- lm(dist ~ speed, data = cars) abline(fit)
> ```
> 
> Currently, Fig. 10.3 in section 10.15 is placed at the page 155, where is section 10.16. It is not intuitive. What about to shrink the figure size of Fig. 10.2 and Fig. 10.3 so that they can be located at the page 154 together?

**Comment by yihui** [comment]
One reviewer mentioned for https://bookdown.org/yihui/rmarkdown-cookbook/bookdown.html:

> The directory tree doesn't quite align on a single page and is interrupted by an image, might be worthwhile fixing.

**Comment by yihui** [comment]
Also make sure words in code are not hyphenated, e.g.,

![broken words in code](https://user-images.githubusercontent.com/19798371/86854769-b26b2500-c07e-11ea-910f-737a1e01966d.png)

**Comment by yihui** [comment]
If possible, we should make sure the tree diagram is not split across two pages in Section 4.20 (this might be hard).

![image](https://user-images.githubusercontent.com/163582/87215670-60d0cd80-c2fe-11ea-930e-770a6e283437.png)

**Comment by yihui** [comment]
![image](https://user-images.githubusercontent.com/163582/89946678-e5a65400-dbe8-11ea-8915-b5c0d431c461.png)

**Comment by yihui** [comment]
![image](https://user-images.githubusercontent.com/163582/89951827-be07b980-dbf1-11ea-862a-c1b401c88138.png)

**Comment by yihui** [comment]
![image](https://user-images.githubusercontent.com/163582/89952507-feb40280-dbf2-11ea-82d2-b936736d6389.png)

**Comment by emilyriederer** [comment]
I feel like I must be missing something obvious, but I have a question on this one. Just to confirm, is the example all on one page currently and the feedback is to be sure this doesn't change? The problem with the current layout isn't obvious to me.

![image](https://user-images.githubusercontent.com/19798371/90077487-e530ba80-dcc7-11ea-9c91-3aa5f7474186.png)

**Comment by yihui** [comment]
The bars are generated by the quote environment. The top and bottom bars should appear on one page. In the above example, the bottom bar needs to be moved to the previous page if possible.
