### ISSUE TITLE
Incorrect LaTeX syntax for Custom Blocks (minipage environment)

### ISSUE THREAD

**Issue by CLRafaelR** [yihui/rmarkdown-cookbook#214]
I think the LaTeX syntax of the `minipage` environment shown in [Custom Blocks](https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html) section is not correct and thus causes an error `Missing number, treated as zero. `

Originally,

```
:::: {.center data-latex=""}

::: {.minipage data-latex="{width=.5\linewidth}"}
This paragraph will be centered on the page, and
its width is 50% of the width of its parent element.
:::

::::
```

but it should be in the following (you may need to remove `width=` in `data-latex`).

```
:::: {.center data-latex=""}

::: {.minipage data-latex="{.5\linewidth}"}
This paragraph will be centered on the page, and
its width is 50% of the width of its parent element.
:::

::::
```

**Comment by yihui** [comment]
You are correct. Fixed now. Thank you!
