### ISSUE TITLE
trouble figuring out how to compile LaTeX to PDF

### ISSUE THREAD

**Issue by archenemies** [yihui/rmarkdown-cookbook#215]
I've been looking over the R package documentation for knitr, and the electronic version of R Markdown Cookbook and can't figure out how to do the very first thing I want to do, which is to compile a .Rnw to a .pdf. Can you please include an explanation for how to do this? There seems to be a lot of great stuff in Chapter 5 on "LaTeX Output" but I can't run the examples. When I change the file I'm editing, I'm supposed to just run pdflatex by myself or what? If so, why is there also a "xelatex" latex_engine? Does this issue not come up for other users?

This is what I have so far:

    > knit("latex-test.Rtex")
    ...
    output file: latex-test.tex

    [1] "latex-test.tex"

Since it is sensitive to input file suffix, I thought this might work:

    > knit("latex-test.Rtex", output="latex-test.pdf")

but the PDF file just contains LaTeX.

I think some basic workflow examples would help here.

Thanks!

**Comment by yihui** [comment]
Where did you read about the `.Rtex` format? I didn't mention it in this book.

I only mentioned `.Rnw`: https://bookdown.org/yihui/rmarkdown-cookbook/latex-hardcore.html The ways to compile Rtex to PDF are the same as Rnw.

**Comment by archenemies** [comment]
Rtex is mentioned in the documentation for `knit`.

**Comment by archenemies** [comment]
Where in the documentation does it say how to get from `.Rnw` to `.pdf`? In my usage of your program, the `knit()` function only takes me to `.tex`.

That is a rephrasing of my initial post.

I noticed that @yihui closed the issue without addressing anything I asked in the initial post. Am I missing something obvious here?

**Comment by yihui** [comment]
Please see the link in my first reply. It did tell you how to compile Rnw to PDF. Did you read it?

BTW, this is the repository for the "R Markdown Cookbook". If your issue is not directly relevant to this book, this repository is probably not the best place to ask your question. Thanks!

**Comment by archenemies** [comment]
* Thank you, I now see that the information is available at the section you linked to

* I found the book difficult to search and navigate, because of the fancy interface. A scrolling continuous-page display would require less mousing and be more accessible via the text-based browser that I primarily use.

* However, I browsed its contents and read the various sections that seemed relevant

* I did not expect that basic information about how to produce the primary output format would be hidden in the very last section of the chapter, "5.12 For hardcore LaTeX users"

* By the way, Googling this question ("knitr compile tex to pdf") also produced unhelpful results, including an SO question with no satisfactory answer: https://stackoverflow.com/questions/41830592/knitr-is-there-a-command-to-compile-a-tex-file-to-a-pdf

* The fact that `knit()` doesn't take you all the way to the final product should be mentioned explicitly on `?knit`. That's a separate issue tracker I know, but if you're not keen to get feedback then I won't bother. But where the examples section of `?knit` has the following:

        library(knitr)
        (f = system.file("examples", "knitr-minimal.Rnw", package = "knitr"))
        knit(f)  # compile to tex

  why not also show users how to get to the final destination? Isn't it a little disappointing to stop halfway?

        library(knitr)
        (f = system.file("examples", "knitr-minimal.Rnw", package = "knitr"))
        knit(f)  # compile to tex
        system2("pdflatex", ...) # tex to pdf
        knit2pdf(f) # or do both in one step

  Also, why not "see also knit2pdf"? There is no occurrence of the string "pdf" in `?knit` at all, which was discouraging.

I hoped it would be helpful to you to have feedbook on the book and software that you're writing, and that is why I took time to comment on some stumbling blocks that I encountered which might be easy for a more experienced user to overlook.

Did you see my question 'When I change the file I'm editing, I'm supposed to just run pdflatex by myself or what? If so, why is there also a "xelatex" latex_engine?'.

Please feel free to let me know if you simply don't want to continue this discussion, but for the record I don't feel that my initial observation of deficiencies in the documentation has been fully received and understood.
