### ISSUE TITLE
A simpler hook for automatic numberLines on code blocks.

### ISSUE THREAD

**Issue by atusy** [yihui/rmarkdown-cookbook#218]
Here is a simpler hook for automatic numberLines on code blocks than hooks on `09-chunk-options.Rmd`.
Shall I work on PR for simplification?

```r
knitr::opts_hooks$set(
  numberLines = function(options) {
    attrs <- paste0("attr.", options$numberLines)
    options[attrs] <- lapply(options[attrs], c, ".numberLines")
    options
  }
)

knitr::opts_chunk$set(
  numberLines = c(
    "source", "output", "message", "warning", "error"
  )
)
```

I do not remember why I have invented quite complex hooks https://github.com/yihui/rmarkdown-cookbook/blob/cf9d349751b0040e79ce8549da35bb50664e99a7/09-chunk-options.Rmd#L542-L581 .

**Comment by yihui** [comment]
Sometimes I don't understand my own code that is unnecessarily complicated, either. Your new code certainly looks much more elegant! Please do open a PR. Thanks a lot!

**Comment by yihui** [comment]
Just did it myself (with you as the committer) since it's simple enough. Thanks again!

**Comment by atusy** [comment]
Thank you so much. I couldn't make time last weekend.
