### ISSUE TITLE
Tag sections by difficulty level, or reorder sections

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#231]
One reviewer said:

> it would be nice if sections are tagged by level (e.g., beginner, intermediate, advanced). The tags especially catch and guide beginner's eye, and help those who skip reading preface.

I'm not sure if it's worth doing, but it sounds like a relatively simple task. I'll leave it to you to decide. I'd probably only indicate advanced topics instead of three levels, e.g., use an asterisk after section headers of advanced topics like `## Manipulate Markdown via Pandoc Lua filters (*)`.

---

One reviewer suggested us reorder sections in https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html

> Sections with similar topics should be placed next to each other. Here is my suggestion:
> 
> * Use variables in chunk options 
> * Do not stop on error
> * Cache time-consuming code chunks 
> * Lazy-loading cached objects
> * Hide code, text output, messages, or plots
> * Hide everything from a chunk
> * Collapse text output blocks into source blocks
> * Reformat R source code
> * Programmatically generate content inside R Markdown
> * Remove leading hashes in text output
> * Multiple graphical output formats for the same plot
> * Post-process plots
> * High-quality graphics
> * Step-by-step plots with low-level plotting functions 
> * Customize the printing of objects in chunks
> * Option hooks

**Comment by cderv** [comment]
@emilyriederer , I can do this one if you want to focus on a more need-writing issue (which I think you are more suited than me) 😉

**Comment by emilyriederer** [comment]
Thanks @cderv ! That sounds great. 

I definitely wouldn't say I'm more suited for writing when I'm least practiced of us all. But since you've been "living" with the book longer, I think you probably have a much better intuition that I do for how it all flows together which is especially helpful for this item!

**Comment by yihui** [comment]
@cderv Please go ahead. Thanks!
