### ISSUE TITLE
A full list of all chunk options

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#233]
One reviewer suggested for https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html:

> As a general note, this chapter could benefit by a summary table of all of the different chunk options currently available for the R language engine.

I'm finally motivated to finish up the PR https://github.com/rbind/yihui/pull/68. After that, @emilyriederer you may copy the .md source to this book, or provide a summary of the options (whichever way you prefer).

**Comment by emilyriederer** [comment]
Thank you! Selfishly, I am very excited to have this one as a quick reference myself 😆

**Comment by yihui** [comment]
I have been hoping to polish up the page https://yihui.org/knitr/options/ for years. It is _the_ single most visited page on my whole website, but the majority of its content was pretty much written in 2012. I have been embarrassed to read it myself many times (poor grammar, lack of clarity and order, etc...).

**Comment by cderv** [comment]
This is a must-have ! I go myself to the knitr options page very often !
@emilyriederer You're not the only one who is excited !

**Comment by yihui** [comment]
@emilyriederer I have finished revising the **knitr** options page: https://yihui.org/knitr/options/ Now you need to decide how to proceed. If you prefer copying the whole page into the book as an appendix, it may make more sense for you to edit the source one more time: https://github.com/rbind/yihui/edit/master/content/knitr/options.md Then copy it to the book. If you prefer providing a shorter summary of all options, it might be a good idea to add a section to https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html.

I'm okay with either way. Selfishly (like you), I wish someone could edit this page one more time as a reviewer, in case I didn't explain certain things clearly enough.

**Comment by emilyriederer** [comment]
Thank you -- this is very exciting! I am excited to start reading tomorrow. I really like the idea of having the full version in the book. I think its very nice to have references in print, so if you agree I think I will ultimately move the full thing in as an appendix and then I will change the line "while the full list is available at https://yihui.org/knitr/options/" in the introduction accordingly.
