### ISSUE TITLE
Write back cover copy

### ISSUE THREAD

**Issue by emilyriederer** [yihui/rmarkdown-cookbook#243]
Back-cover copy should not exceed 350 words. Because this copy will be made available to search
engines, there are some important guidelines:

1. The first few sentences will have the greatest impact.
2. Discuss your book, not the area.
3. When you list a feature, include the benefit or why a reader would want this feature.
4. Use key words in the book title, chapter titles, and the back-cover copy. If you were looking for a book
in this area, what words would you include in your search? Avoid being cute if that means using words
you would not use while searching.
5. If this is a new edition, describe what is new.

The first paragraph states what type of book this is, what is distinctive, and what the prerequisites are. Try
to include what is distinctive in the first sentence. Explain how your book helps the audience solve a
specific problem and this will make the audience clear. A potential reader does not need general
information about the field.

The second paragraph give more details. You can also state what the benefits are; after reading chapters,
what will you be able to do that you previously could not. You can use paragraphs or bullets. Include
what supplements or web materials will be available.

The third paragraph in a few sentences provides biographical details that establish you as an authority in
this area. Include your name, title, affiliation, and any impressive facts. What are your main research
areas, have you edited any journals, won any prizes, published other books, or taught online or short
courses? Details about your Ph.D. or visiting positions usually should not be included.

Note on the preface: If you will offer supplementary material on a website, try to include your address
and ours. Ours may be more stable and we can change our link to your site if necessary.

**Comment by emilyriederer** [comment]
Here is a first draft for feedback. I borrowed heavily from the `Preface` for paragraph 1 and `About` for paragraph 3. This is 300 words so there is some room to spare. I am not sure if I have the right bullets now, and if we should have fewer longer ones or more shorter ones. Please let me know what you think!

---

R Markdown is a powerful tool for combining analysis and reporting into the single document in the spirit of literate programming and reproducible research. Since the birth of the rmarkdown package in early 2014, R Markdown has grown substantially from a package that supports a few output formats (such as HTML, PDF, and Word) to an extensive and diverse ecosystem that enables the creation of books, blogs, scientific articles, websites, and more. Due to its rapid success, this ecosystem is hard to learn completely meaning that R Markdown users, from novices to advanced users, likely do not know all that these packages have to offer. The R Markdown Cookbook confronts this gap by showcasing short, practical examples of wide-ranging tips and tricks to get the most out of these tools.

After reading this book, you will experience how to:

- Enhance your R Markdown content with diagrams, citations, and dynamically generated text
- Streamline your workflow with child documents, code chunk references, and caching
- Control the formatting and layout with Pandoc markdown syntax or by writing custom HTML and LaTeX templates 
- Utilize chunk options and hooks to fine-tune how your code is processed
- Switch between different language engineers to seamlessly incorporate python, D3, and more into your analysis

_The R Markdown Cookbook_ is written by Yihui Xie, a software engineer at RStudio and the prolific leading developer of the R Markdown ecosystem. Xie has created several popular R packages including knitr, bookdown, blogdown, and xaringan and co-authored many more including rmarkdown, shiny, pagedown, and leaflet. Previously, he has published four books which explore these tools in depth, most recently R Markdown: The Definitive Guide (2018). His development work spans both statistical computing and statistical graphs, for which the American Statistical Institute awarded him the 2009 John M Chambers Statistical Software Award.

**Comment by yihui** [comment]
That was quick! I'd reduce my bio (in particular, not to mention so many packages since the space is limited), and avoid adjectives like "prolific" and "leading" :) I just revised it by myself.

Overall it looks good to me (John will make suggestions if he has any). I forgot to mention that if you want examples, here are two that I wrote for the other two books:

https://docs.google.com/document/d/1fylqGKUwlUlnBjqyaIqdqsgopfKehIuUktOWCqiw_k4/edit?usp=sharing
https://docs.google.com/document/d/1LZ0c9eChidPincW6x8gNO6LDnrrYFMSLsGvgTlC0l9I/edit?usp=sharing

**Comment by emilyriederer** [comment]
@cderv - can you please add on to my post above to include a summary of your bio?

**Comment by cderv** [comment]
Here is a suggestion. https://github.com/yihui/rmarkdown-cookbook/issues/243#issuecomment-653660844 What do you think ? 

We are now at 314 words. You have some left for you @emilyriederer but you may need to reduce the first part to get under the 350 words.

**Comment by cderv** [comment]
Thank you @emilyriederer !
