### ISSUE TITLE
Pick marketing keywords

### ISSUE THREAD

**Issue by emilyriederer** [yihui/rmarkdown-cookbook#244]
From John: 

> Please send me six key words or phrases that will improve search results. Do not repeat words in the title as they are already included.

**Comment by emilyriederer** [comment]
Some ideas:

- reproducible research
- literate programming (very relevant but would anyone search on this?)
- open science (related but much more of a stretch)
- rstats (people might be conditioned to search on this from StackExchange and Twitter?)
- LaTeX 
- Pandoc
- knitr 
- rmarkdown (he says not words from title, but I wonder if "R Markown" and "rmarkdown" are functionally different for SEO?)
- code notebook (possibly a common term now with strong Jupyer, Databricks, etc. communities?)

**Comment by cderv** [comment]
What about less specific terms also ? 

* Communication / Communicating
* Documentation / Documenting

About your suggestions:

* Reproducible research, literate programming, Notebook seems ok to me
* If technical term are useful : knitr, Pandoc, Latex seems ok too. 

What about reusing some from the past book, as-is or to get ideas of what is expected ? 
@yihui do you remember what are the words picked for your other books ?

**Comment by yihui** [comment]
The six keywords I used for the Definitive Guide are:

> reproducible research, automatic report generation, data reports, presentations, R Markdown extensions, interactive reports

Like I said in https://github.com/yihui/rmarkdown-cookbook/issues/245#issuecomment-653717159, this task is probably not super important, and I wouldn't think too hard.
