### ISSUE TITLE
Review chapter summaries

### ISSUE THREAD

**Issue by emilyriederer** [yihui/rmarkdown-cookbook#245]
From John:

> They will appear in the book's metadata but not in the book. Abstracts improve search results. They should be 100-200 words each and can be submitted as a separate Word or text file; please don't send a pdf or LaTeX file. We regard this as so important that if abstracts are not supplied, we will use the first few sentences of each chapter. Key words should not be listed separately but use as many as you can in the abstracts. (With final manuscript)

**Comment by emilyriederer** [comment]
@cderv or @yihui , do you have any sense where or how the keywords / abstracts / search results John mentioned are used? I notice some of the chapter beginnings are shorter than the 100-200 word range he mentions, and the read very well for someone actually using the book but are probably not as "packed" with keywords as they could be. 

I wrote denser drafts for the last three chapters that I am including below as an example. Can you please let me know if, based on how these are used, you think it's useful if I continue? I am happy to if packing in more keywords would help for some reason, but if these don't seem meaningfully enough different for the purpose (of which I'm slightly unclear) then it might not be worth it. Just let me know which you prefer please!

--- 

**Chapter 15** 

R Markdown supports many other languages besides R through a variety of language engines implemented in the knitr package. This chapter first explores how custom language engines are implemented with knitr to provide a blueprint for you to develop your own. The remainder of the chapter provides an overview of the broad range of currently-implemented language engines. Options include prominent programming languages such as python, bash, D3, CSS/Sass, SAS, and Stata as well as utility engines such as asis (for verbatim content), cat (for writing contents to a file), and Asymptote (for advanced vector graphics). 

**Chapter 16**

This chapter focuses on managing projects which feature R Markdown documents. When you are working on larger projects or reports, you may not want to put all the text and code in a single R Markdown document. Instead, you may organize them in small units. First, we will explain how to integrate modularized components into an R Markdown document by reading R code from external scripts, sharing code across chunks, and using child documents to split a single R Markdown into multiple more modular pieces. Conversely, we will also explore how R Markdown documents themselves can serve as one small piece of larger projects by demonstrating how these documents can be used for package vignettes, package templates, book chapters with bookdown, or websites with blogdown.

**Chapter 17**

This chapter introduces some tips for working with individual R Markdown documents and developing increasingly large and complex projects which include R Markdown documents. First, we introduce a variety of developer tools available in R and the RStudio IDE and explain how you may configure and customize these. For example, we will review keyboard shortcuts, spell check, different ways to initiate rendering, and options to customize the “Knit” button. Additionally, we will introduce additional R Markdown frameworks or add-on packages to help scale your workflow through parameterized reports, collaborative editing with redoc, conscientious directory structure with workflowr, and email automation with blastula.

**Comment by yihui** [comment]
> do you have any sense where or how the keywords / abstracts / search results John mentioned are used?

To be honest, I don't know and I'm skeptical if they are that useful, so I suggest you not work too hard on them :)

**Comment by emilyriederer** [comment]
In that case, I think all of them are good as is. The only two that stick out as potentially problematic are Chapter 1 and Chapter 15 which have code chunks or code output early in the intro section. If we are concerned about this, I put draft text below. Otherwise, I think we can close this issue.

---

**Chapter 1**

This chapter helps you install, set up, and configure the necessary software to experiment with R Markdown and to implement the various recipes described throughout the book. First, we discuss how to install the **rmarkdown** package from either the most recent stable CRAN release or the development version on GitHub. Next, we discuss different options for installing pandoc and how to locate where pandoc is installed on your computer. Finally, we compare options for installing LaTeX if you wish to generate PDF reports. Here, we recommend the TinyTex distribution which is available through the **tinytex** package and explain how the package can help identify and install missing LaTeX packages. We also recommend that you install the RStudio IDE due to its strong editor support and integration with R Markdown.

**Chapter 15**

R Markdown supports many other languages besides R through a variety of language engines implemented in the knitr package. This chapter first explores how custom language engines are implemented with knitr to provide a blueprint for you to develop your own. The remainder of the chapter provides an overview of the broad range of currently-implemented language engines. Options include prominent programming languages such as python, bash, D3, CSS/Sass, SAS, and Stata as well as utility engines such as asis (for verbatim content), cat (for writing contents to a file), and Asymptote (for advanced vector graphics).

**Comment by yihui** [comment]
Sounds good. Please feel free to send these summaries to John, and tell him that he can use the lead-in sections as summaries for other chapters. Thanks!

**Comment by emilyriederer** [comment]
Will do! Shall I also send at the same time the back cover (#243) and keywords (#244) to close all of these out? 

For keywords, I thought we could recommend the same ones which you used for _The Definitive Guide_, but we can mention the others we thought of in case John has any intuition on how general / specific is preferrable.

**Comment by yihui** [comment]
Yes.
