### ISSUE TITLE
Accessing variable from code chunk in body

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#26]
Use inline code ``` `r variable` ``` with a variable that can be coerce to text.

## Related SO question

* https://stackoverflow.com/questions/10902504/r-markdown-accessing-variable-from-code-chunk-variable-scope
* https://stackoverflow.com/questions/10629416/is-there-an-r-markdown-equivalent-to-sexpr-in-sweave

**Comment by dr-harper** [comment]
This is mentioned within the R Markdown Definitive guide: https://bookdown.org/yihui/rmarkdown/r-code.html However, I feel it is relatively hidden away and there could be a case for some more compelling examples. I'll leave it open for now and come back to it in the future.

**Comment by cderv** [comment]
@yihui I guess if this is covered in the Rmarkdown book we don't add it in the book. 
I suggest we close. What do you think ?

**Comment by yihui** [comment]
I think it is fine to repeat the content in this book. I just added a brief intro to inline R code, because it is extremely useful. Thanks!
