### ISSUE TITLE
Relationship between pandoc, knitr, rmarkdown, bookdown

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#27]
I wonder if this is interesting to begin the cookbook with a reminder of what is what and what does what, with reference to documentations or books for each... 

This is from a SO question. We should close this if we think it is not the right place.

## Related SO question
* https://stackoverflow.com/questions/40563479/relationship-between-r-markdown-knitr-pandoc-and-bookdown

**Comment by dr-harper** [comment]
I have started working on this: https://dr-harper.github.io/rmarkdown-cookbook/r-markdown-components.html

It is still not complete (it was more of an accident that I pushed it to the repository today), but its taking shape. Think it will be a good way to signpost readers to the relevant sections of the book.

**Comment by cderv** [comment]
Nice schematic ! 
And I agree, this is a good roadmap for the reader. I think it will allow to talk about more technical stuff and introduce how all this work together in this chapter. 

I wonder if this is also a place to mention that some tools use rmarkdown to convert to `.md` but do not use necessarily pandoc after. (like `xaringan` or `blogdown` and its [`.Rmarkdown` extension](https://bookdown.org/yihui/blogdown/output-format.html) that use Hugo markdown renderer) 🤔

**Comment by cderv** [comment]
I wonder if it could also be the place to mentioned internal component important to know about when you want to customise further. i.e Mathjax for equation in HTML that have some differences in syntax from LaTex. (related #58)
There maybe other component useful to understand.

**Comment by cderv** [comment]
@yihui this is already mentioned in https://bookdown.org/yihui/rmarkdown-cookbook/r-markdown-components.html

However, I was thinking of this part as way to centralize all information about different format that also use other way than pandoc https://github.com/yihui/rmarkdown-cookbook/issues/27#issuecomment-425677835 I see a lot of question about this Rmarkdown internal.

What do you think ? Should we consider it enough and close ? or leave it open as an improvement for this version or second edition ?

**Comment by yihui** [comment]
I just mentioned xaringan and blogdown. Thanks!
