### ISSUE TITLE
Code chunk font size in Rmarkdown with knitr and latex

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#31]
`.Rnw` had a `size` option. 
How to do with Rmarkdown ? 
Proposed solution:
+ knitr hook ?
+ css ? 
+ other ?

### Related SO question

+ https://stackoverflow.com/questions/25646333/code-chunk-font-size-in-rmarkdown-with-knitr-and-latex

**Comment by cderv** [comment]
In fact it is a knitr option that should work with Rmardown too
https://yihui.name/knitr/options/#code-decoration

Related Knitr Example:
* https://github.com/yihui/knitr-examples/blob/master/044-size.Rnw

**Comment by yihui** [comment]
I don't have a general solution to this problem. I guess it depends on the output format.
