### ISSUE TITLE
The package name rmdrive has changed to trackdown

### ISSUE THREAD

**Issue by psyguy** [yihui/rmarkdown-cookbook#333]
Hi,

The link in these lines redirects to [ekothe/trackdown](https://github.com/ekothe/trackdown/) which seems to be basically the same package renamed.

https://github.com/yihui/rmarkdown-cookbook/blob/05dad6f2ad7ce76a687570ca927b5c08bf92171e/17-workflow.Rmd#L238-L240

**Comment by ClaudioZandonella** [comment]
Hi @cderv,

Together with @filippogambarota, @januz, @Lingtax, and @ekothe, we conducted a complete revision of the `rmdrive` package and renamed it `trackdown`.

The workflow follows the same idea as before, but there are several new features and changes. The main ones are:

- **File Supported**: Both `.Rmd` and `.Rnw` documents are supported
- **Hide Code**: Code in the header of the document (YAML header or LaTeX preamble) and code chunks can be removed from the document when uploading to Google Drive and will be automatically restored during download. This prevents collaborators from inadvertently making changes to the code which might corrupt the file and allows them to focus on the narrative text.
-  **Upload Output**: The actual output document (i.e., the rendered file) can be uploaded to Google Drive in conjunction with the `.Rmd` (or `.Rnw`) document. This helps collaborators to evaluate the overall layout (including figures and tables) and allows them to add comments to suggest and discuss changes.
- **API Speed**:  Now the upload to and download from Google Drive is faster.
-  **Documentation**: Rich e detailed documentation is available at https://ekothe.github.io/trackdown/

Now we are ready to submit the package to CRAN, we are just waiting for the Journal of Open Source Software (JOSS) review ([link](https://github.com/openjournals/joss-reviews/issues/3427)).

I guess that at this point it would be better to update the section  https://bookdown.org/yihui/rmarkdown-cookbook/google-drive.html

I have followed your invitation to submit a PR. See PR #348. 

Let me know if there is any issue or if I can help in some way.

Thanks!
