### ISSUE TITLE
Add an example for ".active" attribute in tabsets recipe?

### ISSUE THREAD

**Issue by maelle** [yihui/rmarkdown-cookbook#338]
:wave: here, I was re-reading https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html (for supporting it in pkgdown https://github.com/r-lib/pkgdown/pull/1694) and was thinking it might make sense to add an explicit example for "By default, the first tab is active (i.e., displayed). If you want a different tab to be displayed initially, you may add the attribute .active to it." just in case readers got a little bit confused?

**Comment by cderv** [comment]
Thanks for the suggestion. If you want to do a PR you're welcome ! 😉 

Otherwise, I'll add an example later. thanks!
