### ISSUE TITLE
Use spell check on a Rmd document ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#34]
This is a question I saw several time. 

First easy solution is to use RStudio spell check. 

Another one is to use [spelling](https://github.com/ropensci/spelling#readme) 📦 with function `spelling::spell_check_files` that knows how to ignore R chunk.

### Related SO questions

* https://stackoverflow.com/questions/36728061/how-can-i-use-spell-check-in-rmarkdown

**Comment by mikey-harper** [comment]
This is a good idea :+1:  I'm going to tag issues which need other packages installed, as I think these would make a good chapter/part.
