### ISSUE TITLE
Using stdin and stdout with knitr

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#345]
If we have room for very advance usage, there is this example answering a question
https://github.com/yihui/knitr/issues/2019

It could be better to have a small blog post about this maybe. 🤔

**Comment by cderv** [comment]
Yes it will be short indeed. Maybe the github issue itself is enough for anyone asking the same question (probably very few people 😅)

**Comment by yihui** [comment]
> probably very few people

That's exactly what I thought. This is the first time I have heard anyone ask this question.

**Comment by cderv** [comment]
So this may not be a good fit for here. I'll removed - too advance and niche topic. Thanks !
