### ISSUE TITLE
How to use Rmardown for package's vignette ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#35]
There is some resources about that but not all as the same place.

+ in the [**R 📦 book**](http://r-pkgs.had.co.nz/vignettes.html#vignette-metadata)
+ in the **Rmarkdown guide** about [`html_vignette` format](https://bookdown.org/yihui/rmarkdown/r-package-vignette.html) but also about using lightweight [prettydoc](https://bookdown.org/yihui/rmarkdown/prettydoc.html#prettydoc-vignettes) as vignette. The last one miss currently one information: use `highlight = "vignette"` to get the same highlithing style that `html_vignette`.
````
---
title: "Vignette Title"
author: "Vignette Author"
output: 
    prettydoc::html_pretty:
        highlight: "vignette" 
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```` 

However, everything could be there and nothing to add in the cookbook. I opened for referencing the SO questions and see if you have ideas on this topic.

### Related SO question
+ https://stackoverflow.com/questions/19372260/how-to-get-rstudio-to-automatically-compile-r-markdown-vignettes

**Comment by nathaneastwood** [comment]
You should include information about [linking package vignettes](https://stackoverflow.com/questions/34946219/linking-r-package-vignettes).

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/package-vignette.html
