### ISSUE TITLE
Package name not bold

### ISSUE THREAD

**Issue by fkohrt** [yihui/rmarkdown-cookbook#353]
The page [Software information and conventions](https://bookdown.org/yihui/rmarkdown-cookbook/software-info.html) states that "package names are in bold text":

https://github.com/yihui/rmarkdown-cookbook/blob/c2f249e9e7cbac4fc82a044ea7f4a35b1f4ca20f/index.Rmd#L124

But due to a [`font-weight` setting](https://github.com/yihui/rmarkdown-cookbook/blob/e660b98/css/style.css#L65-L67) this is actually not the case. Is this on purpose or a bug?

Screenshot:

![Screenshot_2021-07-26 Software information and conventions R Markdown Cookbook](https://user-images.githubusercontent.com/12914806/126991182-1634bc50-5805-4112-a22b-1792b623ec88.png)

**Comment by cderv** [comment]
Hi, 

This is not intended. We'll fix that. Thanks! 

I am surprised we did not saw that before... maybe it does not output the same on all browser. 🤔
