### ISSUE TITLE
 Tips and tricks for working with images and figures in R Markdown documents

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#36]
When digging through my ressources, I sumble upon this blog post that is kind of a cookbook for working with images and figures in HTML. Surely, some ideas of what is useful.
https://www.zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/

### Related GH issues
+ #8 , #25, #17 

### Related SO questions

- [ ] about centering https://stackoverflow.com/questions/24677642/centering-image-and-text-in-r-markdown-for-a-pdf-report
- [ ] Include image with `knitr::include_graphics` ([SO question](https://stackoverflow.com/questions/36350213/how-to-insert-plain-picture-jpeg-png-from-chunk-with-knitr)) - mentioned in [definitive guide](https://bookdown.org/yihui/rmarkdown/r-code.html#figures), and [bookdown](https://bookdown.org/yihui/bookdown/figures.html) with advantages)

### Related knitr example

- [ ] https://github.com/yihui/knitr-examples/blob/master/099-include-graphics.Rmd

**Comment by mikey-harper** [comment]
I think this would be a useful clarification and would be great to include some practical examples. Again, all the options are explained in the R Markdown cookbook but it is not immediately obvious how these can be used.

Images are still one of the most searched areas on Stackoverflow: https://stackoverflow.com/a/25167279/7347699 . The advise which is provided in the top answer is largely out of date.
