### ISSUE TITLE
Update recipe to include file content in  a chunk

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#362]
The recipe is this one https://bookdown.org/yihui/rmarkdown-cookbook/option-code.html

When available in next version of **knitr** following https://github.com/yihui/knitr/commit/545aed32274955be2109150ce1ef4e24fe3732de

````markdown
```{r, code=xfun::read_utf8('your-script.R')}
```
````

could be written

````markdown
```{r, file='your-script.R'}
```
````

This also relates to #360 as it will impact the syntax

**Comment by yihui** [comment]
I just updated this section. But the **cairoDevice** package has been archived on CRAN, so GHA failed: https://github.com/yihui/rmarkdown-cookbook/runs/4723294557?check_suite_focus=true

**Comment by cderv** [comment]
Thank you !
