### ISSUE TITLE
How to change font in Rmarkdown ?

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#37]
In PDF
* https://bookdown.org/yihui/rmarkdown/pdf-document.html#latex-options

in HTML
* Use custom CSS and add dependency

### Related SO questions

- [x] https://stackoverflow.com/questions/24421235/changing-font-in-pdf-produced-by-rmarkdown
- [ ] https://stackoverflow.com/questions/28518368/specify-font-type-on-r-markdown

**Comment by cderv** [comment]
Other issue about font: #24 , #31

**Comment by cderv** [comment]
https://stackoverflow.com/questions/29274501/r-markdown-changing-font-size-and-font-type-in-html-output

**Comment by cderv** [comment]
`fontsize` option has been added for PDF in cb82b3bfda9a7911e92d68a3d0cd3b085280a143
We could add `fontfamily` also

**Comment by yihui** [comment]
`fontfamily` added. Thanks!
