### ISSUE TITLE
Using GitHub Pages and Travis CI to automatically deploy books

### ISSUE THREAD

**Issue by nathaneastwood** [yihui/rmarkdown-cookbook#41]
I'm not entirely sure if you plan to cover GitHub Pages and/or Bookdown with this book, but I [wrote a blog post](https://nathaneastwood.github.io/2017/05/16/automatically-building-testing-and-deploying-bookdown-with-travis-and-github-pages/) last year about how you can use Travis CI to automatically build and deploy your Bookdown book to GitHub Pages. This alleviates the need to build the book yourself and reduces the chance of forgetting to do so and wonder why your changes aren't appearing on your site. I also added `html-proofer` for good measure to check for missing/broken links within the book.

Apologies is this is slightly off topic.

**Comment by mikey-harper** [comment]
This is a good idea, and it is exactly how this book is being built as well (although currently, the book is a bit of a mess as I get the overall layout together).

My main problem with this idea is that as a cookbook, I want the ideas to be fairly easy to copy and paste directly into a document. I think this might more of a technical detail which could be better suited for the bookdown book. I haven't had a chance to compare your post in detail with this chapter but I think they largely cover similar aspects? https://bookdown.org/yihui/bookdown/github.html

I'll add this to the long-term ideas which I will consider once the book is taking a bit more shape.

**Comment by nathaneastwood** [comment]
Ah yes, that is rather similar. I guess my option has the advantage of `html-proofer` but you could easily integrate that into the workflow shown in the Bookdown book.
