### ISSUE TITLE
How RStudio finds pandoc ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#43]
Based on SO question where it is asked how to deal with 
> pandoc version 1.12.3 or higher is required and was not found.

Basically, it is a short tip that RStudio use `RSTUDIO_PANDOC` environment variable to find pandoc, and it that can be set with manually if needed in a script. It is also a way to use another version of PANDOC that the one ship with Rstudio IDE.

Note sure it is worth mentioning in the cookbook, but it could be a small explanation on how things are run in the background. 

I let you close this issue as you see fit - again I opened it to be exhaustive on the top 500 SO QA. 

### Related SO Question
* https://stackoverflow.com/questions/28432607/pandoc-version-1-12-3-or-higher-is-required-and-was-not-found-r-shiny

**Comment by dr-harper** [comment]
I think this is related to issue #27, but it might not fall naturally within the scope of this book.  I am drafting content for this other issue at the moment so I will see if this fits in anywhere naturally.

Is there a particular use case in which this could be practically applied? I would happy to include if there was a compelling scenario.

**Comment by cderv** [comment]
I mainly open this issue to be thorough and report every SO Q&A from top 500, even if we need to close the non interesting one. 
However, I see this as a small but good to know recipe if, for any reason - mainly advanced one I think, one ever need to use another pandoc than the RStudio one, or want to test another pandoc version. 
Will think about other use case, and if none will close this. 
At the end, this indeed may not be a good fit for the book...

**Comment by yihui** [comment]
I feel this is too technical (but extremely useful to advanced users), and I don't really like the hackish `RSTUDIO_PANDOC` method. I'd prefer solving the problem in a more natural way: https://github.com/rstudio/rmarkdown/issues/1785 (i.e. let users set the path to the `pandoc` executable).

I'll think more about it and make a decision soon.
