### ISSUE TITLE
Reminder of markdown syntax

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#44]
I think there will be several questions related to markdown syntax. I opened this issue to regroup them. 
This topic already have a chapter in [Rmarkdown Definitive Guide](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html), so it may not be necessary to do the same here. If you think so, the issue could be closed.

- [ ] Use subscript ([SO question](https://stackoverflow.com/questions/15757695/producing-subscripts-in-r-markdown))
- [ ] multilevel list in ioslide, identical as other markdown syntax by indenting ([SO question](https://stackoverflow.com/questions/26666839/r-how-to-make-second-level-indented-bullet-points-using-rmarkdown-ioslides))
- [ ] Footnote in yaml header (https://stackoverflow.com/questions/35228773/adding-a-footnote-thanks-to-rmarkdown-title-slide)
- [ ] line break ([SO question](https://stackoverflow.com/questions/30057110/line-breaks-in-r-markdown-text-not-code-blocks), [SO question](https://stackoverflow.com/questions/33191744/how-to-add-new-line-in-markdown-presentation))
- [ ] Add a url ([SO question](https://stackoverflow.com/questions/29787850/how-do-i-add-a-url-to-r-markdown))
- [ ] Multi level list ([SO question](https://stackoverflow.com/questions/49084904/r-markdown-bullet-list-with-multiple-levels))

**Comment by dr-harper** [comment]
My current thinking is that we can refer readers to the R Markdown Guide for the basic syntax, and then include an "extended syntax" chapter. This covers quite a few issues that you have raised before, and I think there are lots of other things which might be useful. For example:

- How to indent text within R Markdown: https://stackoverflow.com/questions/47087557/indent-without-adding-a-bullet-point-or-number-in-rmarkdown/52570150#52570150
- How to format text colours. 

I am working on a few of these at the moment, and will push them to the repository soon.

**Comment by cderv** [comment]
A trick to know with Rstudio and spaces inserted by tab 
https://stackoverflow.com/questions/36866916/incremental-nested-lists-in-rmarkdown

**Comment by yihui** [comment]
Given that we have had

- https://bookdown.org/yihui/rmarkdown/markdown-syntax.html
- https://bookdown.org/yihui/bookdown/markdown-syntax.html

it is probably not worth repeating the Markdown syntax in this book.
