### ISSUE TITLE
Recipes about the cache mechanism of knitr in Rmarkdown

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#46]
I think a chapter about the cache mechanism could be worthwhile. There should be some recipes to put in the cookbook about that

About the option in knitr: https://yihui.name/knitr/options/#cache

There is some great ressource:
- Blog post : https://yihui.name/en/2018/06/cache-invalidation/
- Demo : https://yihui.name/knitr/demo/cache/
- knitr GH question: https://github.com/yihui/knitr/issues/1624

## Related SO questions
- [ ] about `cache.lazy=FALSE` useful for very large objects ([SO question](https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script))

## Related knit example

- https://github.com/yihui/knitr-examples/blob/master/017-auto-dependson.Rnw
- about cache levels https://github.com/yihui/knitr-examples/blob/master/101-cache-levels.Rmd

**Comment by dr-harper** [comment]
I think this is related: https://stackoverflow.com/questions/18376008/invalidate-a-chunks-cache-when-uncached-chunk-changes

It is useful if you have chunk cached but want it to update if certain parameters change. For example, if you have graphs which need to be updated when the underlying data is changed.

**Comment by cderv** [comment]
Additions in this in b169e9d

**Comment by cderv** [comment]
Addition about `cache.path` to share cache for different output format in 8ec142089f082e958320a8b254e8dc1613c88916
