### ISSUE TITLE
How to style word document output ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#47]
There is an old article from on the topic of styling a word document output on the [rmarkdown website](https://rmarkdown.rstudio.com/articles_docx.html) 
This cookbook could be an opportunity to update this recipe about word document output styling. The rmarkdown guide does not goes into detail about this and refer to the article. Maybe the whole or some part are worth mentioning  as a recipe in a chapter.

- [ ] About styling table ([SO question](https://stackoverflow.com/questions/37671868/knitr-rmarkdown-docx-tables))

**Comment by dr-harper** [comment]
As this relies on having additional Word files which we can't directly embed in the text, you may wish to set up a separate repository for some word templates like I have for custom blocks here: https://github.com/dr-harper/customBlocks

I am considering storing more ideas in the `examples` subdirectory of this project. However I feel this might make the repository a bit bloated, and it might also hide away useful features.

**Comment by cderv** [comment]
> I am considering storing more ideas in the examples subdirectory of this project. However I feel this might make the repository a bit bloated, and it might also hide away useful features.

Currently, as we have `rmd_subdir: true` in `_bookdown.yml`, all the Rmd in the _examples_ subdirectory are rendered in the book ([chapter 15](https://dr-harper.github.io/rmarkdown-cookbook/eval-after.html#)). I think you notice, right ? 

There is no mechanism to ignore directories (yet because I am 🤔 about a PR to bookdown), just a mechanism to select which subdirectories to look at. I see several options then: 

* Provide the list of subdirectories and ignore _examples_
* move the _example_ directory in a companion repository (`rmarkdown-cookbook-examples` ❔ )
* `rmd_subdir: false` and not use Rmd in subdirectory for the book. Only full rmd, one per chapter or anything, but all in root directory
* `rmd_subdir: "book_rmd"` and move everything related to the book Rmd into one subdirectory.

We have to think about that. I'll open an issue to move the discussion there.
