### ISSUE TITLE
Figure Floating behaviour in LaTeX

### ISSUE THREAD

**Issue by dr-harper** [yihui/rmarkdown-cookbook#49]
A common frustration from new R Markdown users is how figures can float. There are some good tips which can be used to alter this.

https://stackoverflow.com/questions/29696172/how-to-hold-figure-position-with-figure-caption-in-pdf-output-of-knitr

There are some useful solutions. I often use the `flatfer` LaTeX package which prevents figures from floating backwards.

https://tex.stackexchange.com/questions/308635/prevent-positioning-of-figures-before-mentioned-in-the-text
https://tex.stackexchange.com/questions/15706/force-floats-to-be-typeset-after-their-occurrence-in-the-source-text

**Comment by cderv** [comment]
The hook `knitr::hook_movecode()` could be related (and [knitr example](https://github.com/yihui/knitr-examples/blob/master/103-move-float.Rnw))

**Comment by cderv** [comment]
Some knitr example I found where old and may be not suitable anymore. So I am not surprised of this. This is some hidden feature that should not be unravel! 😉

Thank you for testing!

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/figure-placement.html
