### ISSUE TITLE
Provide examples or better documentation on creating new rmarkdown themes

### ISSUE THREAD

**Issue by haozhu233** [yihui/rmarkdown-cookbook#5]
One thing I found that may need some extensive discussions in the definitive guide is how to create new templates from rmarkdown (Chapter 17/18). I'm thinking it would be nice to have a longer chapter talking about how to create a new rmarkdown template under different settings. For example, how to create HTML template with/without bootstrap or how to merge existing LaTeX template with the default pandoc template (like how to understand the syntax in the pandoc latex template file). 

I feel like there are definitely people who have the intention to create new themes for their workplace but they are stopped by the lack of good tutorials on this topic. Also, I sort of get a feeling that there are lots of good templates out there but they are not converted to a rmarkdown-compatible formats. If there are more people who can learn how to do these customizations, I bet @yihui will be happy to get more submissions on themes in future bookdown contests. lol

**Comment by yihui** [comment]
Yes, I will.

This is probably still more suitable for the R Markdown Guide book, though. I absolutely agree that the chapters 17 and 18 need to be extended substantially.

For this cookbook, I think it makes more sense to show examples (instead of documenting how to extend or create new themes), such as your wonderful memor package: https://github.com/hebrewseniorlife/memor.

**Comment by cderv** [comment]
For reference, some examples of html and latex templates were added in 2a4c4f90b9b39defe0c717f535f146c596cc617e and c67a09dda1eda57118ec60b913a0c60d7b5491f1

**Comment by haozhu233** [comment]
@cderv These are really great! I think they covered most of key points here. One other thing I can think of is to provide an example of the syntax for `if else` in the template. 

It might also be helpful to provide a link to a simple dummy template package repository with all these tricks embedded. I remember we have such a thing somewhere online but not sure if I can find it. If not I will just quickly make one later today.

**Comment by cderv** [comment]
> These are really great!

These are surely great as they are from @yihui with its great writing skills. 😊

Adding also example for a if clause seems a great idea. 👍 

>  I remember we have such a thing somewhere online but not sure if I can find it

It does not ring a bell, but if I stumble upon it, I’ll tell you.

**Comment by bblodfon** [comment]
Hi, maybe my [example templates](https://github.com/bblodfon/rtemps) - mostly aimed at reproducible data analyses - also fit in here?

**Comment by yihui** [comment]
@haozhu233 @cderv I just added an `if-else` example: https://bookdown.org/yihui/rmarkdown-cookbook/html-template.html

@bblodfon I added your **rtemps** package to the Definitive Guide book instead: https://bookdown.org/yihui/rmarkdown/template-share.html Thanks!

**Comment by haozhu233** [comment]
@yihui Looks great! Another thing that could be mentioned is that people can also send pandoc argument to template by using `rmarkdown::pandoc_variable_arg` to construct new items and then appended them to `config$pandoc`. This approach is more verbose but gives developer the ability to build more complex logics. 

On the other hand, I can also see why you shouldn't include this piece here as it will make make this section quite complicated... :P

**Comment by yihui** [comment]
@haozhu233 Good suggestion! I agree it is extremely useful to know how to pass arguments to Pandoc via command-line arguments.

**Comment by cderv** [comment]
> how to pass arguments to Pandoc via command-line arguments.

Just creating some links for reference to related other issues on this : #124 and #169
