### ISSUE TITLE
CSS Style tips for tables

### ISSUE THREAD

**Issue by dr-harper** [yihui/rmarkdown-cookbook#51]
Include some ready-made recipes on how to change the appearance of elements in R Markdown, such as tables.

https://stackoverflow.com/questions/24254552/knitr-style-table-with-css

**Comment by cderv** [comment]
Topic related to #8

**Comment by cderv** [comment]
width of table by css : https://stackoverflow.com/questions/28323382/output-table-width-in-rmarkdown
