### ISSUE TITLE
Knitr hooks

### ISSUE THREAD

**Issue by dr-harper** [yihui/rmarkdown-cookbook#53]
Custom hooks are one of the more advanced area of R Markdown which users don't know a lot about from my experience. Some compelling examples of how to use them would be really useful.

Some from @yihui are here: https://gist.github.com/yihui/2629886

**Comment by cderv** [comment]
## Related knitr example

- https://github.com/yihui/knitr-examples/blob/master/033-file-extension.Rnw

**Comment by cderv** [comment]
## Related GH issues
#76

**Comment by cderv** [comment]
[This](https://github.com/rstudio/rmarkdown/issues/1436) could be also interesting to document in the book.

**Comment by cderv** [comment]
One hook added in ff1989ce14503f890afb5835a20e1598092ea64d

**Comment by cderv** [comment]
Chunk hook added in 0c3e2f4fbdc51da11a34b359a1d7e19670188dad
