### ISSUE TITLE
How to change working directory for a Rmd ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#61]
This is mentioned in the Definitive Guide only for [Notebook](https://bookdown.org/yihui/rmarkdown/notebook.html#using-notebooks) whereas it applies for all output. 

Basically, we have
* `opts_chunk$set(root.dir = 'new_dir')` that we can defined in setup chunk
* `knit_root_dir` in `rmarkdown::render` to do it at rendered time (or in the yaml)
* Option in RStudio IDE since [version 1.1](https://blog.rstudio.com/2017/09/13/rstudio-v1.1---the-little-things/)

Maybe a chapter about working directory and useful things to know could be useful, like how to use the `here` 📦 to help with path in a project, without changing the `root.dir`

### Related SO questions

* https://stackoverflow.com/questions/20060518/in-rstudio-rmarkdown-how-to-setwd
* https://stackoverflow.com/questions/25834007/read-table-and-read-csv-both-error-in-rmd
* https://stackoverflow.com/questions/26616202/how-to-solve-this-error-message-in-rmarkdown
* https://stackoverflow.com/questions/21582402/knitr-how-to-set-a-figure-path-in-knit2html-without-using-setwd

**Comment by dr-harper** [comment]
Good idea to discuss working directories, but I think it would be important to explain that normally it is a sign of a bad workflow as it can impact the reproducibility of the code. I think it would be helpful to provide some good and bad examples of when changing directory might be appropriate.

**Comment by cderv** [comment]
> I think it would be important to explain that normally it is a sign of a bad workflow as it can impact the reproducibility of the code. 

I completely agree. The options are still existing in knitr, rmarkdown and rstudio. Explaining them and pointing to `ezknitr` or `here` packages for good worklow (an other great ressource) 

I find that often we don't emphasize enough on the default behavior (execution in the document directory) and that `rmarkdown::render` execute in the current sessions whereas knitr button in a new session. 

We are in sync and I could write on this if needed.

**Comment by dr-harper** [comment]
I would be very happy if you wanted to write this up :) obviously we can agree the exact chapter layout later but I think it would go nicely in a workflow chapter so add the content to the directory `09-workflow`

**Comment by dr-harper** [comment]
> I could write on this if needed

Thought this might be a good one for you to start with if you wanted? Not sure which chapter it would currently fit in, but I think it would go somewhere near the start.

**Comment by cderv** [comment]
Perfect you can assign to me no problem. 

I think at some point we will need to reorganize when we will cover most of the issue. 

I agree on the beginning part.
