### ISSUE TITLE
How to build Rmarkdown content dynamically

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#67]
Parametrized reports are well known but there also other way to programatically create content on the document based on some results or other variables. 

## `knit_expand`

knitr 📦 include a templating mechanism with `knitr_expand` function that works on a file or a text. See help file and [vignette](https://cran.r-project.org/web/packages/knitr/vignettes/knit_expand.html)

## knit child

This is also kind of related to #14.

## generate html or markdown and use `results='asis'`

``````r
```{r one-table-by-species, results='asis'}
for (i in unique(iris$Species)) {
  cat("##", i, "\n")
  cat(knitr::kable(head(iris[iris$Species == i, ,drop = FALSE]), format = "html", row.names = FALSE))
  cat("\n")
}
```
``````

## External 📦 

* [pander](http://rapporter.github.io/pander/#brew-to-pandoc) with _brew to pandoc_
* [whisker](https://github.com/edwindj/whisker) templating framework
* [glue](http://glue.tidyverse.org/) instead of `knitr_expand`

## Related SO question

- [ ] https://stackoverflow.com/questions/21729415/generate-dynamic-r-markdown-blocks
- [ ] https://stackoverflow.com/questions/51158486/create-sections-through-a-loop-with-knitr/

## Related Knitr example

- [ ] https://github.com/yihui/knitr-examples/blob/master/075-knit-expand.Rnw

**Comment by dr-harper** [comment]
Related to this, this is the first time I have had to use `knit_expand`: https://stackoverflow.com/questions/53084808/how-to-insert-page-break-among-subfigures-inside-a-code-chunk-with-knitr#53084808


P.S. sorry for the slight gap in work over the last couple of weeks. Had two journal articles back from peer review at the exact same time, so been occupied sorting those out.

**Comment by cderv** [comment]
I also gave an answer about dynamically building content to create several table from a list of `flextable::regulartable`. 
https://community.rstudio.com/t/mixing-purrr-flextable-and-rmarkdown-for-table-outputs/17312/3

I wonder if it could be improve with `knit_expand`. As of now, it is a great example of use for custom function in `render` chunk option.

**Comment by cderv** [comment]
> I wonder if it could be improve with knit_expand

I built an example with `knit_example` then `knit_child`. I really think that whole example could go in the book.

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/results-asis.html
