### ISSUE TITLE
Ideas : Add a part about tips for non R chunks ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#7]
I saw this question on RStudio community
https://community.rstudio.com/t/unique-paths-between-rstudio-notebook-and-rstudio-terminal/7936/5

Looks to me like a tip hard to find and could fit into a cookbook. Maybe they are other out there. 

## Related Knitr Example
- [Demo](https://yihui.name/knitr/demo/engines/)  where they are link to knitr examples
- Knitr examples: [python](https://github.com/yihui/knitr-examples/blob/master/023-engine-python.Rmd), [c](https://github.com/yihui/knitr-examples/blob/master/090-engine-c.Rmd), [fortran](https://github.com/yihui/knitr-examples/blob/master/111-engine-fortran.Rmd), [sql](https://github.com/yihui/knitr-examples/blob/master/115-engine-sql.Rmd), [awk](https://github.com/yihui/knitr-examples/blob/master/024-engine-awk.Rmd), [ruby](https://github.com/yihui/knitr-examples/blob/master/025-engine-ruby.Rmd), [haskell](https://github.com/yihui/knitr-examples/blob/master/026-engine-haskell.Rmd), [bash](https://github.com/yihui/knitr-examples/blob/master/027-engine-bash.Rmd), [perl](https://github.com/yihui/knitr-examples/blob/master/028-engine-perl.Rmd), [dot](https://github.com/yihui/knitr-examples/blob/master/057-engine-dot.Rmd), [tikz](https://github.com/yihui/knitr-examples/blob/master/058-engine-tikz.Rmd), [sas](https://github.com/yihui/knitr-examples/blob/master/060-engine-sas.Rmd), [coffeescript](https://github.com/yihui/knitr-examples/blob/master/080-engine-coffeescript.Rmd), [polyglot](https://github.com/yihui/knitr-examples/blob/master/106-polyglot.Rmd), [go](https://github.com/yihui/knitr-examples/blob/master/118-engine-go.Rmd)
- about `engine = 'asy'` for [asymptote](http://asymptote.sourceforge.net/) graph https://github.com/yihui/knitr-examples/blob/master/093-knitr-asy.Rmd
- example of usage for several engine : https://github.com/yihui/knitr-examples/blob/master/106-polyglot.Rmd

**Comment by mikey-harper** [comment]
Are there any further uses of the `engine.opts` argument you have found? I like the concept, but I am not sure it is immediately clear how this may be used by a reader. Potentially it warrants a more detailed explanation within other technical guidance.

Happy to include it if we can find some compelling use cases :)

**Comment by cderv** [comment]
Related to #128

**Comment by cderv** [comment]
`asis` engine added: aa37cb1cc6e19e1a575647270ac4ff1c176768d6
Custom engine added: 769c4baef3d604f533520da9de477a745aef11fe

maybe still missing some other recipes to show the different engine and options ?

**Comment by yihui** [comment]
Just added a few more. Please let me know if there are still more. I plan to finish the draft of this (long overdue) book by the end of this month, so I'll probably leave some ideas behind. Thanks!
