### ISSUE TITLE
How to make conditional block in Rmarkdown

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#72]
A small recipe about conditional block

* using `if`  in inline r block : ``` `r if(test) {do}` ```
* using chunk option `eval` with a variable define
````
```{r conditional, eval = variable-test}
do_something()
```
````

##  Related SO question

- [x] https://stackoverflow.com/questions/25407102/conditionally-display-a-block-of-text-in-r-markdown
- [ ] https://stackoverflow.com/questions/25354903/conditional-echo-or-eval-or-include-in-rmarkdown-chunks
- [ ] https://stackoverflow.com/questions/39550732/is-there-a-way-to-have-conditional-markdown-chunk-execution-in-rmarkdown
- [ ] https://stackoverflow.com/questions/25837990/preventing-a-chunk-run-in-rmarkdown

### Related Knitr example

- https://github.com/yihui/knitr-examples/blob/master/011-conditional-eval.Rnw

**Comment by cderv** [comment]
Very interesting use case based on this : apply `eval = TRUE` based on the name (label) of the chunk
https://stackoverflow.com/questions/26993254/how-to-get-chunk-name-in-knitr

An opportunity to show `opts_current$get("label")`

**Comment by cderv** [comment]
I did not know this was also possible with Latex (see [the knitr example](https://github.com/yihui/knitr-examples/blob/master/036-latex-if.Rnw))
```tex
\documentclass{article}
\newif\ifmyboolean
\begin{document}

<<setup>>=
myboolean='true' # or set it to 'false'
@
% assign true or false to myboolean
\myboolean\Sexpr{myboolean}

\ifmyboolean
hello, foo!
\else
hey, bar!
\fi

\end{document}
```

**Comment by cderv** [comment]
Some recipes already added: 
* a068891463726557a507e7a252c9e9de49640f5c about block conditional to package
* aa37cb1cc6e19e1a575647270ac4ff1c176768d6 about `asis` engine for conditional text in Rmd.

**Comment by cderv** [comment]
Related to #113 

I think we can add more recipes based on examples in questions

**Comment by yihui** [comment]
I think these are special cases or applications of https://bookdown.org/yihui/rmarkdown-cookbook/chunk-variable.html so we can probably close this one.
