### ISSUE TITLE
add an exemple about how to add a logo in header or footer

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#73]
Based on this [SO question](https://stackoverflow.com/questions/27982052/insert-a-logo-in-upper-right-corner-of-r-markdown-pdf-document), this could be a good complement to this chapter
https://dr-harper.github.io/rmarkdown-cookbook/add-custom-headers-and-fsooters.html

**Comment by cderv** [comment]
Related : 
https://stackoverflow.com/questions/43009788/insert-a-logo-in-upper-right-corner-of-r-markdown-html-document

uses html in code and css styling.
````r 
```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path(R.home("doc"), "html", "logo.jpg")), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;')
```
````

**Comment by cderv** [comment]
Related:
https://stackoverflow.com/questions/29389149/add-image-in-title-page-of-rmarkdown-pdf

uses the _titling_ latex package

```yaml
header-includes:
- \usepackage{titling}
- \pretitle{\begin{center}\LARGE\includegraphics[width=12cm]{my_graphic.png}\\[\bigskipamount]}
- \posttitle{\end{center}}
````

**Comment by cderv** [comment]
for ioslide

**Comment by dr-harper** [comment]
> Related:
> https://stackoverflow.com/questions/29389149/add-image-in-title-page-of-rmarkdown-pdf
> 
> uses the _titling_ latex package
> 
> ```yaml
> header-includes:
> - \usepackage{titling}
> - \pretitle{\begin{center}\LARGE\includegraphics[width=12cm]{my_graphic.png}\\[\bigskipamount]}
> - \posttitle{\end{center}}
> ```

This example is slightly different to the other examples, in that it is only for the cover page. But I have added it in e8693bd.

I am starting to see limitations in the way I am structuring the chapters. There are going to be some shorter sections like this where there is not a lot to really say. I will stick with the current format for now, but I was thinking that it might be an idea to start each chapter with a section of "10 quick tips" or something for people to quickly jump into, and then having longer sections for some of the ore complicated ideas.

**Comment by nmolanog** [comment]
in the html answer, logo overlaps with header, in deed the logo has its own div an is not nested in header div.
