### ISSUE TITLE
How to reproduce the run all chunk button from RStudio 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#78]
See this SO Question
https://stackoverflow.com/questions/24753969/knitr-run-all-chunks-in-an-rmarkdown-document

and answer from andrie. 

> Using Run all chunks is equivalent to:
> * Create a temporary R file
> * Use knitr::purl to extract all the R chunks into the temp file
> * Use source() to run the file
> * Delete the temp file

I find it interesting to know about it if we find room this somewhere

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/purl.html
