### ISSUE TITLE
How to format table in Rmarkdown ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#8]
I find it a very frequent questions with lots of solutions. It is also not so simple because some solution are one-output-type only (you don't format the same on pdf, html and word).

There a long thread about that here 
https://community.rstudio.com/t/output-nice-looking-formatted-tables/1084

and very interesting comparison [here](https://hughjonesd.github.io/huxtable/design-principles.html) by the creator of huxtable.

Currently, the idea is only to mention `kableExtra`. We could include more example and point toward packages (flextable, huxtable, and a few other)

### Related SO question
* https://stackoverflow.com/questions/15488350/programmatically-creating-markdown-tables-in-r-with-knitr
* https://stackoverflow.com/questions/25166624/insert-picture-table-in-r-markdown
* https://stackoverflow.com/questions/19997242/simple-manual-rmarkdown-tables-that-look-good-in-html-pdf-and-docx
* https://stackoverflow.com/questions/20942466/creating-good-kable-output-in-rstudio
* https://stackoverflow.com/questions/40699550/how-to-format-a-complex-table-for-rmarkdown-pdf-output
* https://stackoverflow.com/questions/41900335/adjusting-width-of-tables-made-with-kable-in-rmarkdown-documents
* https://stackoverflow.com/questions/29267605/rmarkdown-kable-width-issues
* https://stackoverflow.com/questions/40840986/knitrkable-is-there-a-way-to-reduce-the-font-size
* https://stackoverflow.com/questions/33319457/display-a-data-frame-as-table-in-r-markdown

**Comment by cderv** [comment]
Another related SO question on [how to have multicolumn table in table](https://stackoverflow.com/questions/13984470/possible-to-create-latex-multicolumns-in-xtable)

Don't know if it is better to open another issue  for this or not.

**Comment by cderv** [comment]
in some way related : How to do interactive table : DT 📦 
https://stackoverflow.com/questions/27120002/is-it-possible-to-have-sortable-interactive-table-in-rmarkdown

**Comment by cderv** [comment]
Conditional highlighting in HTML table 
https://stackoverflow.com/questions/27114926/r-conditional-row-highlighting-in-html-table-created-using-xtable-or-kable
I think 📦  like huxtable or formattable can help on this

**Comment by cderv** [comment]
how to add spakline to tables
* https://github.com/htmlwidgets/sparkline

https://stackoverflow.com/questions/32841221/add-sparkline-graph-to-a-table

**Comment by cderv** [comment]
About regression table
https://stackoverflow.com/questions/24342162/regression-tables-in-markdown-format-for-flexible-use-in-r-markdown-v2

It is a question I had at work also. Some 📦 really help with that and may need to be promoted (like  huxtable 📦 with [`hexreg`](https://hughjonesd.github.io/huxtable/huxreg.html))

**Comment by cderv** [comment]
Add a caption to a Hand-made table 
https://stackoverflow.com/questions/33965560/r-markdown-table-with-a-caption
Related to #105, and #106 
Pandoc feature for [tables](http://pandoc.org/MANUAL.html#tables)
> Extension: table_captions
A caption may optionally be provided with all 4 kinds of tables (as illustrated in the examples below). A caption is a paragraph beginning with the string Table: (or just :), which will be stripped off. It may appear either before or after the table.

**Comment by cderv** [comment]
Split long table in several small one
https://stackoverflow.com/questions/34813408/r-markdown-kable-break-table-width-into-multiple-tables-below-each-other

**Comment by cderv** [comment]
format inside cells 
https://stackoverflow.com/questions/28166168/how-to-change-fontface-bold-italics-for-a-cell-in-a-kable-table-in-rmarkdown

**Comment by cderv** [comment]
https://stackoverflow.com/questions/26971785/adapt-pandoc-table-column-width

**Comment by cderv** [comment]
Related Knitr examples:
* https://github.com/yihui/knitr-examples/blob/master/040-grid-table.Rnw

**Comment by cderv** [comment]
All this has now a place to live in the book
https://dr-harper.github.io/rmarkdown-cookbook/tables.html

I will try to add piece by piece.

**Comment by cderv** [comment]
Some more on `kableExtra` here 0a31369dd81576ac911db77852b62eaf0e2ed3d4 and about other packages in (34ed6fcea110e14b3e0210467d0ba63d05ad2b6b and 3e9134ff3042dd995f4b68735f5ea544ed59f75e)

There are still a few tricks link up there that could we worth adding I think. 
However, some of the answer in SO are with pander's `pandoc.table`

**Comment by yihui** [comment]
I think I have at least given all of these packages a mention at https://bookdown.org/yihui/rmarkdown-cookbook/table-other.html. I don't think I'll have time to write in more detail, so I'm going to close this issue. If I missed any package names, please feel free to add them to this section. Thanks!
