### ISSUE TITLE
How to disable viewer in RStudio 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#80]
and how to use browser instead. 

A small tips worth mentioning if it fits somewhere

# Related SO queston

https://stackoverflow.com/questions/31697945/do-not-open-rstudio-internal-browser-after-knitting

**Comment by dr-harper** [comment]
Do you think there is sufficient content for a section on RStudio? I agree it could be useful to show this :)

**Comment by cderv** [comment]
I think we may find other recipes that could be part of a chapter on RStudio and Rmarkdown. 
For example, we could add some useful addin to know about, or some useful snippets to add ? 
Also, there are already other issue related to Rmarkdown behavior with RStudio (#43 , #78 , #43 or #11)

We'll keep on stocking idea, and see how we could organise this.

**Comment by dr-harper** [comment]
This RStudio section is starting to come together here: https://github.com/dr-harper/rmarkdown-cookbook/blob/master/book/09-workflow/rstudio-integration.Rmd . This one will be fairly easy to add to this.
