### ISSUE TITLE
How to rotate a table (landscape vs portrait) 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#81]
This is related to other issues about tables #8 and #51 

There seems to be solution in third party 📦 about table
* KableExtra
* Stargazer
* maybe `xtable:::print.xtable` and `floating.environment` latex and and some additional latex packages

# Related SO question 
- [ ] https://stackoverflow.com/questions/25849814/rstudio-rmarkdown-both-portrait-and-landscape-layout-in-a-single-pdf/
- [ ] https://stackoverflow.com/questions/21840878/rotate-a-table-from-r-markdown-in-pdf

**Comment by cderv** [comment]
This are features that seems possible to using Third party 📦 . As they are mentioned it could be enough.

**Comment by yihui** [comment]
`landscape()` was briefly mentioned in 13.2.4: https://bookdown.org/yihui/rmarkdown-cookbook/kableextra.html
