### ISSUE TITLE
How to add unnumbered subsection

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#90]
See one community.rstudio.com
https://community.rstudio.com/t/turning-off-section-numbering-in-bookdown-output/16272

This Syntaxe 
```
## sub-section {-#mysubsection1}
```

There could be other solution (as it is used in R4DS) and also it could have been mentioned already in bookdown but I did not find it.

**Comment by dr-harper** [comment]
This is similar https://stackoverflow.com/questions/34382869/how-to-make-part-of-rmarkdown-document-without-section-numbering

The key part is that `{-}` turns off the number. In the case you have referenced, I think they have also assigned the section a pandoc [section reference](https://stackoverflow.com/questions/34382869/how-to-make-part-of-rmarkdown-document-without-section-numbering) which makes it easier to cross-reference the section without using the full name.

Still useful to mention though :)

**Comment by cderv** [comment]
Yes it is the combination of both that is interesting. We'll see where it could fit in the book.
