### ISSUE TITLE
How to control figure position ? 

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#94]
This topic is about aligning and positioning plots and images on the page.

This related to #49 (maybe a duplicate ?) and by topic to #17 . 

## Related SO question

* https://stackoverflow.com/questions/40932462/controlling-placement-of-figures-with-the-knitrinclude-graphics-function
* https://stackoverflow.com/questions/42486617/knitr-ignoring-fig-pos
* https://stackoverflow.com/questions/40414270/r-how-to-center-output-in-r-markdown
* https://stackoverflow.com/questions/29696172/how-to-hold-figure-position-with-figure-caption-in-pdf-output-of-knitr

**Comment by cderv** [comment]
Two columns layout for figures:
https://stackoverflow.com/questions/28000062/tables-and-figures-side-by-side-in-knitr-or-rmarkdown-beamer

**Comment by cderv** [comment]
Another opend [issue](https://github.com/yihui/knitr/issues/1696) in knitr on that

**Comment by cderv** [comment]
Example of this with bootstrap class 
https://gist.github.com/cderv/385abca9b6952be3f3db9c7bf401d9d1

**Comment by yihui** [comment]
I think we have covered some of these posts, e.g.

- https://bookdown.org/yihui/rmarkdown-cookbook/figure-placement.html
- https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html
- https://bookdown.org/yihui/rmarkdown-cookbook/figures-side.html

**Comment by plantarum** [comment]
The suggestion to include the float package, and use the R chunk:

    knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")

doesn't appear to do anything for me. There's nothing in the generated LaTeX to reflect the !H setting, and the images in the pdf do still float.

If instead I add the raw LaTeX 

    \floatplacement{figure}{H}

At the top of my RMarkdown file (after including float), my images do get placed where I expect. Is there something broken with the way that option gets set, or am I missing something?
