### ISSUE TITLE
How to put text below a tab section ?

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#95]
It is small trick but maybe worth mentioning if it can goes somewhere in the book.

```r
## title {.tabset .tabset-fade}
content above tabbed region.

### tab 1 

tab content 1

### tab 2

tab content 2

##

content below tabbed region
```

Add an empty hearder (`##`) without tab to stop the tab section 

* https://stackoverflow.com/questions/38062706/rmarkdown-tabbed-and-untabbed-headings

**Comment by yihui** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html
