### ISSUE TITLE
How to create cross-format table in bookdown using kableExtra

### ISSUE THREAD

**Issue by haozhu233** [yihui/rmarkdown-cookbook#96]
https://bookdown.org/yihui/rmarkdown/r-code.html#tables

As @yihui said in bookdown, "it is difficult to make a complex table work for both PDF and HTML output". If people really want to use the same code to generate code for both HTML and PDF, they may expect to do some extra work. I created an example to show how to create complex table in PDF, HTML and EPUB. Here is the link: https://haozhu233.github.io/kableExtra/bookdown/index.html

**Comment by cderv** [comment]
Thank you. This is also related by topic to #8. 
Not sure how we will organize it regarding all solutions for table formating. 🤔 
Regarding, `kableExtra`, there could be all book on all you need to know to get the full out of it.
