### ISSUE TITLE
How to write some special character both for pdf and html output ?

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#99]
This is something I never encounter but if it is a thing, we should find a place somewhere for this trick. 

The question is about `°` character for HTML and PDF output. It seems that it is not valid for pdf and you need `$^\circ$`. `&deg` seems to work. I believe this is an [encoding thing](http://www.fileformat.info/info/unicode/char/b0/index.htm)

https://stackoverflow.com/questions/26234119/how-can-i-write-a-degree-symbol-in-rmarkdown2-for-html-and-pdf-output

What are your thoughts on this one ? did you deal with this issue in the past ?

**Comment by haozhu233** [comment]
It seems like `30$^\circ$` will work for both html and latex? Maybe this thing can be mentioned somewhere in the multi-format chap. https://github.com/dr-harper/rmarkdown-cookbook/tree/master/06-multiformat

**Comment by cderv** [comment]
Yeah you're right. It will work because `\circ` is recognized by MathJax and Latex. However, I find it odd to use this trick of superscript + drawing circle to get the degree character. 🤔 However, that may be the simplest...

**Comment by cderv** [comment]
The example in the SO question seem to work now
````r
---
title: test
output: 
  pdf_document: default
  html_document: default
---

some text with a special character °
```
So I'll close and ignore this question
